### ISSUE TITLE
Ubuntu 16,18 machine user constant not showing

### ISSUE THREAD

**Issue by aimdharma1990** [Ylianst/MeshAgent#103]
Following will the desktop manager

Ubuntu 16, Yes user is logged in, Gnome is the desktop

Also getting error in
uncaughtException1: Error: => EventEmitter.emit(): Event dispatch for 'end' on 'http.WebSocketStream.decoded' threw an exception: TypeError: undefined not callable (property 'close' of [object Object]) in method '()'

Note: Those machine having Team viewer installed already

**Comment by krayon007** [comment]
I'm just linking [this](https://github.com/Ylianst/MeshCentral/issues/3008) issue from the Server repo that has more activity on it with regards to this particular issue
