### ISSUE TITLE
Error installing meshagent on windows 2012 server (64 bit)

### ISSUE THREAD

**Issue by lokasoft** [Ylianst/MeshAgent#105]
Installing using the meshagent64, service installation is OK but then while writing the firewall rules I am getting several error messages and after that it hangs.
This happened on two 2012 servers. The servers are in a hyper-v cluster configuration.
I used the same installer on a couple of 2012 server VM's and there is installed OK.

After that I tried it a second time, I see it is unstalling previous version, then installing server again. After that it again hangs in writing the firewall rules, now without error messages, it just hangs.
After Ctrl+C and manually starting the agent is seems to work, issue is only in writing the firewall rules.

Any ideas?
Are there some prerequisites about powershell version or windows updates?

Lex

**Comment by krayon007** [comment]
Which Mesh Central version are you using? It currently tries to use PowerShell to write the PowerShell rules, and falls back to netsh if PowerShell isn't supported. I think the current version should ignore PowerShell errors when writing the rules, but I know older versions would not succeed if PowerShell was blocked.

**Comment by lokasoft** [comment]
Version 0.9.7. We just installed it a couple of days ago. Downloaded the agent from that version.

Lex

**Comment by lokasoft** [comment]
On windows server 2012 R2 it worked fine, problem is only on windows server 2012. We only had the problem on the two physical servers, not on a few 2012 VM's we had. Unfortunately this is a live site and we can not use it for testing.
Also this is the only site where we still have 2012, all our other sites are at least 2012 R2 where we did not have the problem.

**Comment by krayon007** [comment]
Ok, all my Server 2012 test setups were R2, so I'm going to build a non-R2 Server 2012 test system to debug...

**Comment by lokasoft** [comment]
Greet!
