### ISSUE TITLE
Agents register correctly when connecting directly, but incorrectly when MeshCentral behind proxy using IIS ARR

### ISSUE THREAD

**Issue by inzi** [Ylianst/MeshAgent#106]
Server:
Windows Server 2012
IIS 10
Node Version: v12.16.2.
MeshCentral version: 0.9.7
Agent Version: 64bit service, background & interactive: 2021-Aug-5 13:47:56-0700, 64bit

Description:

Adding agent to MeshCentral when MeshCentral is behind a proxy fails to behave as expected.

Recreation Steps:

Basic install of MeshCentral, bound to port 80, 443. Login, add group, add new agent (software).
Agent registers and behaves as expected.

Stop Mesh Central. Change ports, add alias ports, add certUrl, and configuration for functioning behind a proxy.

Configure IIS w/ARR as reverse proxy pointing at MeshCentral.
Configure headers in URL ReWrite for forwarded For, host, etc.

Restart IIS & MeshCentral.

Login, agent behaves as expected.

Add 2nd agent on another computer (win64, software, background & interactive).

2nd Agent appears in dashboard, but Desktop, Shell, and agent details are missing. 

Stop IIS, MeshCentral. 

Revert MeshCentral to basic configuration (ports 80, 443).

Start MeshCentral, restart 2nd agent - 2nd agent appears in dashboard, behaves as expected, providing Desktop, Shell, etc.

Stop MeshCentral, replace config with Aliased Config.

Start IIS, start MeshCentral

2nd agent appears in dashboard, behaves as expected, providing Desktop, Shell, etc.

Steps attempted to resolve:
I attempted to tell the agent to clear its core, and upload a recovery core, and more.

Details:

MeshCentral logs that it has successfully retrieves the SSL from the IIS server provided by the CertURL value in Domains section.

I've gone through multiple steps to determine how to recreate this issue.  I've tried enabling extra logging but I am not seeing anything indicating a failure by the agent to 'register' with the system.

Evidence indicates that during the initial connection, the agent is not able to complete the registration process. 

I am potentially passing headers incorrectly, but am unable to determine exactly what's happening.

Debug logging by the agent would be helpful.

Note: I'm new to MeshCentral, so I may have missed something in the configuration.

Next Steps on my side:

I'm going to make a page that dumps all headers and start this on IIS on a different port, then configure the proxy to verify the headers are passing correctly
![Screen Shot 2021-08-21 at 1 18 23 PM](https://user-images.githubusercontent.com/889113/130331462-778cdba3-3243-48da-b739-5f1e116f1e73.png)
![Screen Shot 2021-08-21 at 1 18 08 PM](https://user-images.githubusercontent.com/889113/130331463-0a4e408b-7008-4305-bf1d-2c1656feeb9c.png)
.

**Comment by inzi** [comment]
Of note - this appears to be the same issue as documented here:
https://github.com/Ylianst/MeshCentral/issues/89

I've added "AgentConfig": [ "webSocketMaskOverride=1" ],  to my config.

**Comment by inzi** [comment]
I've verified my headers are being passed to MeshCentral correctly, as well. 

In examining the MeshAgent.db file - the agent that works correctly has considerably more data than the one that doesn't work correctly.

opening meshagent.db in notepad++ shows the ServerID tag to be identical - but in the agent that works, there are 108,607 bytes before that. On the one that does NOT work, there are only 27,883 bytes.

It appears that the agent is not successfully initializing itself with the server if being added while MeshCentral is behind a proxy.

**Comment by inzi** [comment]
I added "ignoreagenthashcheck": true to my config.

Downloaded the agent again, ran update.

No change.

I have agent errors to be logged to server, now, as well.  No entries.

**Comment by inzi** [comment]
This is my current MeshCentral config.json file:

`{
   "settings": {
      "cert": "mesh.xxxxxxxx.com", 
      "wanonly": true, 
      "_minify": true, 
      "port": 480, 
	  "redirPort": 88,
	  "redirAliasPort": 80,
	  "portBind": "127.0.0.1",
	  "AliasPort": 443,
	  "TlsOffload": "127.0.0.1",
	  "AuthLog":"C:\\ProdApps\\MeshCentral\\logs\\auth.log",
	  "Log":"main,web,webrequest,cert",
	  "agentLogDump": true,
	  "agentLogDump": true,
	  "Plugins": {"enabled":true},
        "AllowLoginToken": true,
        "AllowFraming": true,
        "WebRTC": true,
        "ignoreagenthashcheck": false,	  
      "letsencrypt": {
         "email": "xxxxxxxx", 
         "names": "mesh.xxxxxxxx.com", 
         "rsaKeySize": 3072, 
         "production": false
      }
   }, 
   "domains": {
      "": {
         "title": "INZI Mesh",
		 "AgentConfig": [ "webSocketMaskOverride=1" ],
		 "certUrl": "https://mesh.xxxxxxxx.com"
      }
   }, 
   "smtp": {
      "host": "smtp.office365.com", 
      "port": 587, 
      "from": "xxxxxxx", 
      "user": "xxxxxxxx", 
      "pass": "xxxxxxxx, 
      "tls": false
   }
}`

**Comment by inzi** [comment]
I added:
"CookieIpCheck": false,
    "CookieEncoding": "hex",

To config.

**Comment by inzi** [comment]
I started my meshcentral server with the --agentupdatetest 1 flag.

When I did this, ALL my agents are connected, but do not report their version, and desktop / remote control ability is not available.

**Comment by inzi** [comment]
Closing this - as this appears to be IIS ARR specific as far as I can tell.

Using NGINX, this behaves exactly as it should. 

Behind IIS ARR, it does not.  This has to be related to IIS's implementation of a reverse proxy or my configuration.

Of note, it's important to enable host header retention in IIS AAR, and there is no GUI. It can be done with this command:

Preserve host header for reverse proxy

%windir%\system32\inetsrv\appcmd.exe set config -section:system.webServer/proxy -preserveHostHeader:true /commit:apphost

**Comment by Ylianst** [comment]
For future reference, [the related issue is here](https://github.com/Ylianst/MeshCentral/issues/3047).
