### ISSUE TITLE
How to compile MeshAgent by Visual Studio?

### ISSUE THREAD

**Issue by magicgis** [Ylianst/MeshAgent#107]
when i use Visual Studio 2019 to open the project and try to compile it, it comes to some error:
https://i.loli.net/2021/09/02/Qklno3IuMJfAO9Y.png

and some library link is not found:
https://i.loli.net/2021/09/02/AqlSIv5EHpatebP.png

so how to compile on vs2019?

**Comment by krayon007** [comment]
I see you selected the configuration `Debug_NoOpenSSL`. Please use either `Debug` or `Release`
The NoOpenSSL was for a different usage, but it looks like I need to update it. But regardless, OpenSSL is required to communicate with the Server.

**Comment by magicgis** [comment]
ok, it works on Debug and Release.thanks.
