### ISSUE TITLE
Compiled windows agent not working

### ISSUE THREAD

**Issue by hchkim** [Ylianst/MeshAgent#11]
Dear developer,
Thank you for making a good system. I have some questions.

Q1) I built Windows Agent using Visual Studio 2015. I built it with release option and changed file name MeshService.exe to MeshAgent.exe. After then run "MeshAgent.exe run" on command line.

MeshCentral2 Agent
Connecting to: wss://x.com:8080/agent.ashx
Connected.

I seems connection is successful, but the agent did not actually appear on the MeshCentral screen. 
Is there a way to know why this is happening? I want to know the registration and login mechanism.

Q2) What is the difference between meshservice_signed.exe and meshservice.exe? Meshcentral uses meshservice_signed.exe.

**Comment by Ylianst** [comment]
Q1) If you can, run the server like this "node node_modules/meshcentral --debug 1" and look for any errors when the agent connects. Also, it's possible your .msg file does not have the right "meshid" in it, so the server does not know where to make this agent show up. Make sure you use a valid "meshid".

Q2) When the _signed file is present, MeshCentral will serve that one first. If not present, it will serve the unsigned one. I sign the MeshAgent with a authenticode certificate that I pay for. However, it's not necessary to make things work.

**Comment by hchkim** [comment]
Thank you for reply.
I did it the way you let me know. But it failed. 
**********************************************************************
AUTH MSG: 
...
Error msg: Agent connected with bad signature, holding connection
**********************************************************************

The binaries you have built will work properly showed the message below.
**********************************************************************
AUTH MSG:
...
MSG:
...
Verified agent connection to 
**********************************************************************
I just changed only MeshAgent.exe binary to compiled binary with same meshid, .msh file. Meshcentral server is also same.

But I don't know why it is happen. Please let me know how do I can check more at agent side.

1. Clone from https://github.com/Ylianst/MeshAgent
2. Build it with x86, Release
3. Move Release/MeshService.exe to C:\Program Files (x86)\Mesh Agent\MeshAgent.exe (File renaming)
4. Execute MeshAgent.exe run

It failed to connect.
