### ISSUE TITLE
QUESTION - Is it possible to open an ssh connection from MeshCentral Server to a Client

### ISSUE THREAD

**Issue by LPJon** [Ylianst/MeshAgent#112]
Hello,
     So I had a question about opening up connections with Meshctrl. I currently have a backup system setup on the same server as MeshCentral. This backup system performs backups with ssh. My goal is to use Meshctrl to open an ssh connection from Mesh Central Server to one of it's clients and then execute an ssh command to start the backup through the ssh connection and then close the connection once it's finished. Could you point me in the right direction as far as finding the commands if this is even possible?

**Comment by Ylianst** [comment]
Yes, MeshCMD can do 2FA by specifying `--token 123456` or you can set `--emailtoken` or `--smstoken` to receive a token using Email or SMS. This said, a better option is to create login token for your account in the "My Account" tab:

![image](https://user-images.githubusercontent.com/1319013/138575651-2aba0927-a5ab-4f51-a601-e2b4afb516ed.png)

Call it the "Automated Backup" token. You will get a username and password you can give to MeshCMD that will not have 2FA and can be revoked at any time. Also, the special account can't change your account settings (email, password, image) and can't delete your account, etc. It's perfect for this type of automated usage.
