### ISSUE TITLE
meshagent service keeps deactivating on Pi

### ISSUE THREAD

**Issue by frakman1** [Ylianst/MeshAgent#118]
When running Arch Linux ARM on Pi4, the meshagent keeps deactivating for no apparent reason. Running `systemd start meshagent.service` results in immediate deactivation with no error logs. 

`journalctl -u meshagent.service`:

```
Jan 06 07:27:21 pikvm1 systemd[1]: Started meshagent background service.
Jan 06 07:27:43 pikvm1 systemd[1]: meshagent.service: Deactivated successfully.
Jan 06 07:37:50 pikvm1 systemd[1]: Started meshagent background service.
Jan 06 07:38:11 pikvm1 systemd[1]: meshagent.service: Deactivated successfully.
```

There should be better logging for why it was deactivated to aid in troubleshooting.
The agent seems to have been running fine for < 1 day after initial installation.

The device itself is still accessible via ssh on an adjacent network device and can access the internet.

**Comment by frakman1** [comment]
**Some more information about this device:**
It's a [PiKVM](https://docs.pikvm.org/flashing_os/) (Pi4). The image used is located [here](https://files.pikvm.org/images/v2-hdmiusb-rpi4-latest.img.xz
):
One peculiar thing about this OS is that it runs in read-only mode to extend SD card lifetime and avoid filesystem corruption.
The commands `ro` and `rw` set read-only and read-write modes respectively.

**Some observations:**
When set to read-only, the agent will fail immediately when launched.
When I set it to read-write, the agent stays up. 
Later, when switched to read-only while the agent is running, then some time later, the agent will fail and disconnect from server

Since the PiKVM is meant to run in read-only mode, and can run basically every other function without  any issues, I would hope that the agent can also run while file-system is in read-only mode too.
I've included the Pi image used in the hope that you can try it and confirm my results and hopefully make meshagent compatible with PiKVM.

**Comment by krayon007** [comment]
Thanks, I will take a look. The agent is supposed to be able to run in a read only mode. One thing I need to check is if the log file is not writable.

**Comment by krayon007** [comment]
I'm going to track this with [this issue](https://github.com/Ylianst/MeshAgent/issues/14) since they are both about read-only mode.
