### ISSUE TITLE
GUI issue: Info window too small for German translation

### ISSUE THREAD

**Issue by jacotec** [Ylianst/MeshAgent#122]
The info window of the agent is too small to display the info text in German, that looks ugly:

![image](https://user-images.githubusercontent.com/3321655/151769699-debbf32d-e972-4030-bf75-bde1844e9cf6.png)

**Comment by krayon007** [comment]
![image](https://user-images.githubusercontent.com/29240564/152218936-c647ff7a-a5d6-4854-bdf8-87e476f1256b.png)

We redid the installer UI, so in the next agent update this will be fixed. This is what it will look like in german in the next update.

**Comment by jacotec** [comment]
@krayon007 I love that design!!! It's awesome!

**Comment by JSuenram** [comment]
> ![image](https://user-images.githubusercontent.com/29240564/152218936-c647ff7a-a5d6-4854-bdf8-87e476f1256b.png)
> 
> We redid the installer UI, so in the next agent update this will be fixed. This is what it will look like in german in the next update.

Just a small little suggestion.... put Connect-Button to the left, followed by Update and then Uninstall... I think that is a little bit more intuitive....

**Comment by krayon007** [comment]
By the way @jacotec if you can let me know the proper way to translate the "Connection Details" and "Update" I can make sure that is included in the default German translation.

**Comment by jacotec** [comment]
@krayon007 "Updates" is very common in German, if you want to have absolutely German it depends on the function of the button:

If is is it only there when an update is available and it starts the update, use "Aktualiseren".

If it checks for updates and lists possible Updates, use "Aktualiserungen"

"Connection Details" is "Verbindungsinformationen"

**Comment by krayon007** [comment]
Oh, ok. I just wanted to make sure we didn't accidentally overlook the translation and accidentally left it in English.

**Comment by jacotec** [comment]
@krayon007 Will the broken MacOS installer also be fixed in the upcoming release?

**Comment by krayon007** [comment]
> @krayon007 Will the broken MacOS installer also be fixed in the upcoming release?

Just so I can correlate the threads, which issue# are you referring to? (Are you referring to the permissions issue?)

**Comment by Ylianst** [comment]
The original issue here is fixed. Please open a new issue if not related to the original one. We have to do this since it's difficult to track many requests on the issue number.
