### ISSUE TITLE
macOS GateKeeper prevent meshAgent to install

### ISSUE THREAD

**Issue by cadegenn** [Ylianst/MeshAgent#123]
Hi,

We recently start playing with meshCentral and so far it fulfill many requirements.
But as part of our deployment procedure, we did not manage to deploy silently meshAgent using munki. The meshAgent installer seems to not be signed by an Apple Developer Id.

Thank you for the hard work.

**Comment by krayon007** [comment]
That was intentional, since this is an open source project.

**Comment by cadegenn** [comment]
Hmmmm. Unfortunately I was expecting this kind of answer.
I was referring to the installer. We tried to deploy with munki.
If I find we have an Apple Developer Id here at work, I will try to sign it and test it.
thank you.
