### ISSUE TITLE
adding meshagent command line switch on installation

### ISSUE THREAD

**Issue by cadegenn** [Ylianst/MeshAgent#124]
Hi again,

It would be great if meshAgent install could have a couple of new command line switch like for example
- `-servername fqdn.domain.tld` to connect to given server
- `-groupname "full name to group"` to automatically add/move/replace the machine to given group (or default group if it does not exist)
This way, meshAgent would be neutral, server-agnostic and group-agnostic. I believe it is not the case for the moment as the installer we download is already configured to connect to the server and group it was downloaded from.

Thank you very much.
best regards.

**Comment by krayon007** [comment]
If you are looking to be able to connect to any server, you'll need more fields than that, including the certificate hash of the server. The easiest way to accomplish what you are talking about, is to simply place the meshagent.msh configuration file in the same folder as the agent. Then when you install the agent, use the switch `--copy-msh=1`, which will tell the installer to use and copy the msh that is on disc.

**Comment by cadegenn** [comment]
Hi,
Thank you for the answer.
I didn't know about the `--copy-msh` switch. I'll give it a try.
thanks.
