### ISSUE TITLE
Windows: Shift + Cursor

### ISSUE THREAD

**Issue by LordBritish2000** [Ylianst/MeshAgent#126]
Hello!

There is a strange bug in the Windows Agent at different Windows Versions, You cant select multiple Chars ore Listviewentrys with Shift+Cursor.

Working functionality on Microsoft Windows Server 2012 R2 Datacenter - 9600 / Agent Version Jan 7 2022
![image](https://user-images.githubusercontent.com/97960058/154236980-bbbb73a7-2a1f-4703-86bf-cac6208235ec.png)

On Most other Windows with the same Agent you cant select multiple Lines chars with shift
not working f.E.: Microsoft Windows 10 Pro - 17763 /  Agent Version Jan 7 2022
![image](https://user-images.githubusercontent.com/97960058/154237519-1f916b38-af0f-40fe-a644-8174d88059a1.png)

It does not mather if you control via Web or via Meshcentral Router, same behaviour. Locally all keyevents for KVM seem to be ok, but i Found no explanation for this error in the Agent code:

https://github.com/Ylianst/MeshAgent/blob/master/meshcore/KVM/Windows/kvm.c
```
case MNG_KVM_KEY: // Key
		{
			if (size != 6) break;
			KeyAction(block[5], block[4]);
			break;
		}
```

https://github.com/Ylianst/MeshAgent/blob/master/meshcore/KVM/Windows/input.c
```
void KeyAction(unsigned char keycode, int up)
{
	INPUT key;
	HWND windowHandle = GetForegroundWindow();
	if (windowHandle == NULL) return;
	SetForegroundWindow(windowHandle);
	key.type = INPUT_KEYBOARD;
	key.ki.wVk = keycode;
	key.ki.dwFlags = 0;
	if (up == 1) key.ki.dwFlags = KEYEVENTF_KEYUP;									// 1 = UP
	else if (up == 3) key.ki.dwFlags = KEYEVENTF_EXTENDEDKEY | KEYEVENTF_KEYUP;		// 3 = EXUP
	else if (up == 4) key.ki.dwFlags = KEYEVENTF_EXTENDEDKEY;						// 4 = EXDOWN
	key.ki.time = 0;
	key.ki.wScan = (WORD)MapVirtualKey((UINT)keycode, MAPVK_VK_TO_VSC);				// This is required to make RDP client work.
	key.ki.dwExtraInfo = GetMessageExtraInfo();
	SendInput(1, &key, sizeof(INPUT));
	//printf("KEY keycode: %d, up: %d, scan: %d\r\n", keycode, up, key.ki.wScan);
}
```

Where does the unneccesary "LShiftKey - WM_KEYUP" come from?

If someone could solve this, would be very cool, I use meshcentral hours a day...

With kind regards, Flynn

**Comment by krayon007** [comment]
Interesting... Looking into it...

**Comment by krayon007** [comment]
Ok, I figured it out... First things first, I was not seeing the errant WM_KEYUP like you were showing, so I'm not sure about that... I was only seeing LSHIFT_DOWN, LEFT_DOWN, LEFT_UP, LSHIFT_UP.

But anyways, the problem was that UP/DOWN, and a few others are EXTENDED_KEYS, so the flags should have included KEYEVENTF_EXTENDEDKEY.
That means the up flag should have been 3 or 4 with the arrow key, not 0 or 1. Luckily, this should only involve a server side fix...

**Comment by LordBritish2000** [comment]
Hey, Great. That was the last thing that was annoying. You do really great work, thank you!

**Comment by Ylianst** [comment]
I just checked in a fix in MeshCentral for this. Indeed, the keyboard mapping was not correct. The fix will be in MeshCentral v0.9.88.

**Comment by LordBritish2000** [comment]
cool! thx

**Comment by LordBritish2000** [comment]
In meshcentral in browser it works now. I think in win "mesh-router" it´s still the same behaviour.
