### ISSUE TITLE
Mesh agent crash on Windows 10

### ISSUE THREAD

**Issue by knkumar93** [Ylianst/MeshAgent#130]
Hi,

Getting below crash message. No clear pattern about crash, it happens randomly.

> Faulting application name: MeshAgent.exe, version: 0.2.1.3, time stamp: 0x612d4568
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00f0fc84
Faulting process id: 0x1ebc
Faulting application start time: 0x01d8449339b39396
Faulting application path: C:\Program Files (x86)\Mesh Agent\MeshAgent.exe
Faulting module path: unknown
Report Id: bfd9fe88-b7bd-4c19-8c46-5ea9b213ff3c
Faulting package full name: 
Faulting package-relative application ID: 
>

Enabled "coreDumpEnabled=1" flag in meshagent.msh file, but crash dumps are not generating.

OS information: Windows 10 21H2.

Please suggest any other way to approach this problem?

**Comment by krayon007** [comment]
Is there a .dmp file that got generated?

**Comment by knkumar93** [comment]
No it is not generated.

Luckily I found a pattern here. Whenever mesh agent crashed, before 1 or 2 second below event is printing. 

> Updated Windows Defender status successfully to SECURITY_PRODUCT_STATE_ON.

For testing purpose, excluded mesh agent folder in defender scan and ran quick scan, the crash was not observed.

**Comment by knkumar93** [comment]
Unfortunately, for some time the above mentioned was working. But after a day (may be after system reboot), again it is crashing and defender related event is printing. The added exclusion is still in place.

**Comment by krayon007** [comment]
When running the following command, what does it report?
`MeshAgent -info`

**Comment by knkumar93** [comment]
I couldn't get the environment again to reproduce this issue. I will open issue when I come across this again. Closing for now.
