### ISSUE TITLE
Mesh Agent not installed

### ISSUE THREAD

**Issue by panenka** [Ylianst/MeshAgent#133]
Trying to install meshagent64-Group.exe. On one computer installed and running, on second computer not installed, not created folder. Not found any error message.

**Comment by krayon007** [comment]
Are the two computers configured identically? Any errors reported by AntiVirus?

**Comment by krayon007** [comment]
Also, which install method did you use? If you install the agent from the command line, like:
`meshagent64-group -fullinstall`
Does it report any errors that way?

**Comment by panenka** [comment]
With -fullinstall installed without any problems. Don't understand.
