### ISSUE TITLE
Tray application

### ISSUE THREAD

**Issue by panenka** [Ylianst/MeshAgent#134]
I'm trying Mesh Agent a I'm looking for visible part of application. I think that it could be Assistant, but I don't know which version to use, so maybe I'm wrong. When Assistant has been started, all variants shows such Direct connection as default and not the Mesh Agent. I can select Mesh Agent, but I don't know how to make this as default and use Assistant as visible part of Mesh Agent to the user interface. When Direct connection has been used, a new, duplicate item in MeshCentral console has been created for each computer I try.  Thanks for your help.

**Comment by Ylianst** [comment]
Hi. You may need to send screen shorts of your issue. When using MeshCentral Assistant, you can use it to monitor the existing background agent or you can using it to directly connect to the server. Yes, if you use it for direct connection, you will see a second device on the MeshCentral server. In this image, there is a "System Tray, Monitor Only" mode:

![image](https://user-images.githubusercontent.com/1319013/165138375-c4140d6e-383e-4393-9878-19552585afec.png)

The "Monitor Only" mode will not have direct connect. Hope that helps.

**Comment by panenka** [comment]
I've been tried Agent from 1.0.0.12 now but it is not working as expected. Direct connection is selected after startup, not the Mesh Agent.
![image](https://user-images.githubusercontent.com/9946446/165683723-aae389f3-6e5f-4173-91b2-71c14b5a96d1.png)

**Comment by Ylianst** [comment]
Ok. You likely downloaded MeshCentral Assistant to also operate as an agent and so, direct connection is available. If you don't want direct connection, download the one with only agent monitoring. Also, clear any .msh file in the MeshCentral Assistant folder.
