### ISSUE TITLE
Meshagent is malicious?

### ISSUE THREAD

**Issue by jakrsvk** [Ylianst/MeshAgent#136]
7 security vendors and no sandboxes flagged this file as malicious.
https://www.virustotal.com/gui/file/b00a43a8b719b36f6f02be7ed843f8d28c7cc47492e1526f54a4d0241c7d3071/detection
<img width="935" alt="meshagent" src="https://user-images.githubusercontent.com/104613303/165889849-a8627b5b-473d-42dc-9946-d9b19b5cbef1.png">

**Comment by Belvedus2** [comment]
I think, it's because of a lot of trojan use the source of meshcentral. 

So it depend on how you use it.

**Comment by jakrsvk** [comment]
I use it as service

**Comment by Ylianst** [comment]
This is a common issue. A lot of people use the MeshAgent to do bad things. It is certainly remote control software and so, it's right for AV vendors to mark it at least with a warning. You can sign the agent and lock it to only connect to your server, I demonstrate this in a [YouTube video here](https://www.youtube.com/watch?v=HZj9igSn-sY).

If you are doing remote support, you can use MeshCentral Assistant. That tool is code signed by myself and requires user consent, but will not show as a problem with AV software.

I will not that the MeshAgent ONLY communicates with the your server. So, it's only a malware if you use it like one.

**Comment by jakrsvk** [comment]
Thank's for your answer.
I didn't quite catch this part.
>I will not that the MeshAgent ONLY communicates with the your server. So, it's only a malware if you use it like one.
Can you explain it to me?

**Comment by krayon007** [comment]
> Thank's for your answer. I didn't quite catch this part.
> 
> > I will not that the MeshAgent ONLY communicates with the your server. So, it's only a malware if you use it like one.
> > Can you explain it to me?

I think he meant that if you code sign the agent yourself, we have support so you can lock it to your server, such that the signed binary would only be a le to connect to your server. If someone tried to modify the config to connect to a different server, the agent would refuse to connect.. He was saying that the agent, like many remote tools, is only "bad" if you use it in a bad way.

**Comment by Ylianst** [comment]
I was just saying that the mesh agent is no malware, it will only do what you want you want it to do.
