### ISSUE TITLE
Unable to open database AGENT not showing up

### ISSUE THREAD

**Issue by drock850** [Ylianst/MeshAgent#138]
First what an awesome tool.
Second I am not a programmer. 

I am new to this and am setting up for a student lab at my school.

I am troubleshooting why my agent is not showing up in devices.
I ran mesh agent run and am getting the unable to open database error.
Well that is just one error.
I have installed on my main DC.
And edited the config.json file. 
  "settings": {
    "_cert": "10.61.1.7:444",         
    "_WANonly": true,
    "_LANonly": true,
    "_sessionKey": "MyReallySecretPassword1",
    "_port": 443,
    "_aliasPort": 443,
    "_redirPort": 80,
    "_redirAliasPort": 80

Being new to this I am not sure what else to do.
My lab server is on its own domain with inside the school. and the 10.61 address is ping able on the school network.

? 

Help please.

**Comment by drock850** [comment]
How about this.
I installed it on a Windows 10 VM and it works fine.
10.61.x.x

So I have other VMs with 2 NICs and my agent is seen in Mesh Central but can not connect to it from Mesh Central.
10.61.x.x
192.168.131.x
They are on different Domains.

Is there any way to connect my lab domain to my school domain?

The only thing I can think to do now is to have separate Mesh Centrals running on each lab domain. 

And brings me back to the point of having a centralized management tool.

**Comment by drock850** [comment]
Added second NIC to lab server groups.
And Agent installs just fine.
I can see them all now.

Windows 10 in on the school lab domain.
Installed IIS 
Trying to setup remote access to our Mesh Central install.
Thus far I can externally hit the ISS default page.
Internally I can hit the Mesh Central install. 

Anyone have any suggestions on how to setup external access Mesh Central?

**Comment by krayon007** [comment]
> I ran mesh agent run and am getting the unable to open database error. 

This is because the background service is still running, so it locked the database. To run the agent from the console, you must stop the background service first. You can do that from the command line by running the following command from an elevated command prompt, substituting `Mesh Agent` with your service name. `Mesh Agent` is the default

`wmic service "Mesh Agent" call stopservice`

**Comment by krayon007** [comment]
> So I have other VMs with 2 NICs and my agent is seen in Mesh Central but can not connect to it from Mesh Central. 10.61.x.x 192.168.131.x They are on different Domains.

Inside your VM, can you run the following command, substituting `MeshAgent` with the executable name

`MeshAgent -exec "console.log(_MSH().MeshServer);process.exit();"`

The returned url, is it a domain name, or an IP address? Does the DNS resolution work, and does it ping correctly?

**Comment by drock850** [comment]
Was a firewall issue. Resolved now.
Thank you for all suggestions.
