### ISSUE TITLE
MeshAgent Automatic Rollout

### ISSUE THREAD

**Issue by xDankau** [Ylianst/MeshAgent#143]
Hello,

we use MeshCentral in a school environment. The clients are divided into 6 different groups, which are the different parts of the building for us. When distributing images to around 400 computers, we also want to automatically distribute the MeshAgent to all computers.
The computers are all named after the building parts + room names, so recognizing the computers is quite simple for us.

But now we encounter the problem that we don't get the MeshAgent installed automatically.
To automate the installation, we wrote a batch script that checks the name of the computer and, depending on the name, installs the associated MeshAgent with a -fullinstall.

We tried an installation via our imaging program "FOG Project" (as a snap-in).
When installing the respective agent using the snap-in function, we get code 2, but unfortunately we can't do much with it.
Manual execution of our scripts works.

Since we already use quite a lot of group policies, we actually want to avoid running the script using group policies.

What does this code 2 refer to?

**Comment by krayon007** [comment]
I'm not sure I follow. Are you saying the installation returns an error code 2 when trying to automate the installation?

How command does the script invoke to attempt installation? What user is the script executed as?

**Comment by xDankau** [comment]
So in fact, we tried 2 different methods of installing the meshagent.

Version 1 - batch script:

start /b PowerShell.exe -ExecutionPolicy Bypass -Command "& '"Path\Mesh_A.ps1'"

Mesh_A.ps1:
Start-Process -Wait -FilePath 'Path\meshagent64-ComputerA.exe' -ArgumentList '-fullinstall' -PassThru

Version 2 - Batch script:

@echo off

:checkPrivileges
NET FILE 1>NUL 2>NUL
if '%errorlevel%' == '0' ( goto gotPrivileges ) else ( goto getPrivileges )
 
:getPrivileges
if '%1'=='ELEV' (echo ELEV & shift /1 & goto gotPrivileges)
 
setlocal DisableDelayedExpansion
set "batchPath=%~0"
setlocal EnableDelayedExpansion
ECHO Set UAC = CreateObject^("Shell.Application"^) > "%temp%\OEgetPrivileges.vbs"
ECHO args = "ELEV " >> "%temp%\OEgetPrivileges.vbs"
ECHO For Each strArg in WScript.Arguments >> "%temp%\OEgetPrivileges.vbs"
ECHO args = args ^& strArg ^& " "  >> "%temp%\OEgetPrivileges.vbs"
ECHO Next >> "%temp%\OEgetPrivileges.vbs"
ECHO UAC.ShellExecute "!batchPath!", args, "", "runas", 1 >> "%temp%\OEgetPrivileges.vbs"
"%SystemRoot%\System32\WScript.exe" "%temp%\OEgetPrivileges.vbs" %*
exit /B
 
:gotPrivileges

echo "Installation Gebäude A"
IF NOT EXIST "%ProgramFiles%\Mesh Agent\MeshAgent.exe" ("Path\meshagent64-ComputerA.exe" -fullinstall)

exit

We ran into the problem that we have to use admin rights to be able to use the scripts. Both ways are an available option. Manually executing those 2 scripts installs the meshagent just fine.

The first Version just bypasses the need to use admin rights, the second one sets the executed rights as admin.

I can see the code 2 returned in our imaging program and the installation does not go through.

**Comment by xDankau** [comment]
So
