### ISSUE TITLE
Firewall flagging meshagent_osx64 as modified

### ISSUE THREAD

**Issue by frakman1** [Ylianst/MeshAgent#144]
Should I be concerned about this?
Little Snitch on Mac flagged meshagent all of a sudden out of nowhere.
I use meshcentral.com's public server to manage devices.
Is 52.32.58.254 (on amazonaws) a valid IP address destination?

![image_2022-07-08_18-20-33](https://user-images.githubusercontent.com/5826484/178078770-9347c0ea-0f7d-4b09-abeb-1f71db7f6254.png)

![image_2022-07-08_18-16-00](https://user-images.githubusercontent.com/5826484/178078772-b4c5786d-d70a-426c-86e6-48a76c4b47ba.png)

**Comment by krayon007** [comment]
That appears to be the actual IP of the public meshcentral server.

**Comment by frakman1** [comment]
Good to know. Thank you.
