### ISSUE TITLE
No scheme in MeshAgent installer's connection string

### ISSUE THREAD

**Issue by phorcys420** [Ylianst/MeshAgent#152]
**Describe your issue**
The scheme is missing in the connection string.
I could not figure out what this is related to

**Screenshots**
My setup (://) :
![image](https://user-images.githubusercontent.com/57866459/188444926-c6172e94-bf55-47cd-9df9-5dc35c674abc.png)

Normal setup (wss://) :
![image](https://user-images.githubusercontent.com/57866459/188436538-3770b30c-8758-45cc-b219-ac9b16fae066.png)

**Server Software (please complete the following information):**
 - OS: Ubuntou 20.04
 - Virtualization: Docker
 - Network: LAN/WAN, reverse proxy (apache2 <-> caddy <-> meshcentral), ssl offload
 - Version: 1.0.82
 - Node: 18.8.0

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over LAN
 - Browser: Firefox Developer Edition

**Client Device (please complete the following information):**
 - Device: Laptop
 - OS: Windows
 - Network: Remote over LAN

**Your config.json file**
```
{
   "$schema": "http://info.meshcentral.com/downloads/meshcentral-config-schema.json",
   "settings": {
      "cert": "[...]",
      "_WANonly": true,
      "_LANonly": true,
      "_sessionKey": "[...]",
      "port": 420,
      "AliasPort": 443,
      "redirPort": 80,
      "_redirAliasPort": 80,
      "AgentPong": 300,
      "TLSOffload": true,
      "SelfUpdate": false,
      "AllowFraming": false,
      "mongodb": "mongodb://mongodb:27017/mesh",
      "mongodbcol": "mesh",
      "WebRTC": false
   },
   "domains":{
      "": {
         "_title":"[...]",
         "_title2":"[...]",

         "auth":"ldap",
         "ldapUserName":"sAMAccountName",
         "ldapUserKey": "sAMAccountname",
         "ldapUserBinaryKey":"objectSid",
         "ldapUserEmail": "mail",
         "ldapUserRealname": "name",
         "ldapUserPhoneNumber": "ipPhone",
         "ldapOptions": {
            "url": "ldap://[...]",
            "bindDN": "[...]",
            "bindProperty": "userPrincipalName",
            "bindCredentials": "[...]"
            "reconnect": true,
            "searchBase": "[...]",
            "searchFilter":"(sAMAccountName={{username}})"
         },

         "certUrl": "https://[...]"
      },

      "local": {
         "_title": "MeshCentral",
         "_title2": "MeshCentral",
         "_minify": true,
         "NewAccounts": false,
         "_userNameIsEmail": true
      }
   },
   "_letsencrypt":{
      "__comment__": "Requires NodeJS 8.x or better, Go to https://letsdebug.net/ first before>",
      "_email": "myemail@mydomain.com",
      "_names": "myserver.mydomain.com",
      "production": false
   }
}
```

**Comment by phorcys420** [comment]
> If you can email me your msh file, I can look into why the scheme isnt being displayed.. Thanks!

I've just started out using MeshCentral, where can I find the said file ?

**Comment by krayon007** [comment]
If you go to "Program Files" or whatever the localized folder for that is, you should find a MeshCentral folder, that contains the agent. You'll find a meshagent.msh file there. It's a text file with configuration information.

**Comment by phorcys420** [comment]
Why via email and not send it here ? (I will redact some info anyways)
I mean I'm fine with email but I was just wondering

**Comment by krayon007** [comment]
I was interested in the connection details in the configuration, as that directly effect how it's rendered in the dialog box, etc. But you probably don't want to post those types of things on a public forum.

**Comment by phorcys420** [comment]
I sent it to you via the e-mail in your GH profile, do you think it might be caused by the lenght of the domain?

**Comment by krayon007** [comment]
Ok yes, it looks like the url itself was too long to fit in the dialog. I'll fix that. I'll see if I can change the type, so that it can at least scroll or something. I think if I change the field to a read only text box, it might work like that. I'll have to run some tests.

**Comment by krayon007** [comment]
![TestToolTip](https://user-images.githubusercontent.com/29240564/192888601-9b98a6c5-ad76-4b66-a12c-2ef9a6fee0be.png)

Ok, I fixed this issue. I modified the text field, so it puts an ellipses (...) and truncates the text if it is too long, and made it display a tooltip if you hover over the field, which will show the full url. This will be in the next agent update when Ylian gets back.

**Comment by phorcys420** [comment]
great ! thanks, I think it will prevent some confusion for other people :)
