### ISSUE TITLE
Linux Installer.

### ISSUE THREAD

**Issue by uwejan** [Ylianst/MeshAgent#155]
Hi,
1. Where do i start in case of creating a linux installer screen + a screen to enable / disable the service.
2. I wish the documentation has some guidlines indicating what path has the screens for windows. that would help me modify the installer, add/drop screens and allow me have better understanding in general of what c files are resposible for what exactly.

Thank you very much.

**Comment by krayon007** [comment]
The installer is contained within agent-installer.js found in the modules folder, which handles the actual installation. The screens are contained within interactive.js also in the modules folder. It is slightly modified and included as meshinstall-linux.js on the server. The screens are created using zenity or kdialog depending on which platform you are on.

**Comment by uwejan** [comment]
Thank you, Am going to cehck the mentioned file soon.  Perhaps will be able to have an idea how screens works. What file can i find the application API, lets say wanted to check the service status/enable/disable on one of my screens? Is it all .js related or do i need any knowledge on the c fiels side, if so what c files do i need to work on?

**Comment by krayon007** [comment]
If you look at interactive.js, it should have a section there where it is querying the service status. All that is abstracted by service-manager.js

**Comment by uwejan** [comment]
Yes, i just had a look at message-box. Are you saying there is no need to deal with C files for any api calls, its all apstracted in .js files. What would be the easiest way to test my screens before compiling the agent.

**Comment by krayon007** [comment]
It depends on which file you modify, but the easiest way is to run the js directly, like this:

`./meshagent interactive.js`

**Comment by uwejan** [comment]
```
 ./meshagent_x86-64 modules/interactive.js 
Interactive Setup Utility successfully created.
```
Then the command line exits. I tried running the agent afterward with argument it runs only on command line.

**Comment by uwejan** [comment]
I am also trying to get the service status with pure js. am getting ,
```
* _GenericMarshal in ./modules/service-manager.js                                                                                                                                    friendly-errors 11:48:54
* child_process in ./modules/service-manager.js                                                                                                                                      friendly-errors 11:48:54
* fs in ./modules/service-manager.js                                                                                                                                                 friendly-errors 11:48:54
* lib-finder in ./modules/service-manager.js                                                                                                                                         friendly-errors 11:48:54
* process-manager in ./modules/service-manager.js                                                                                                                                    friendly-errors 11:48:54
* promise in ./modules/service-manager.js                                                                                                                                            friendly-errors 11:48:54
* service-manager in ./modules/service-manager.js                                                                                                                                    friendly-errors 11:48:54
* user-sessions in ./modules/service-manager.js  
```

**Comment by krayon007** [comment]
How did you invoke service-manager to get those errors?

**Comment by uwejan** [comment]
```
let s
try { s = require('../modules/service-manager').manager.getService('meshagent'); } catch (e) { }
```

**Comment by krayon007** [comment]
I'll put together some samples, and upload it into the snippets folder. I'll post back when I have that pushed.

**Comment by krayon007** [comment]
Ok, I uploaded a sample, showing how to find a service, using service-manager, as well as how to show the service running state, binary location, etc...

You can run the fragment like the following, substituting the service name you are looking for, in place of meshagent
`./meshagent_x86-64 snippets/service-manager-test.js meshagent`

**Comment by krayon007** [comment]
![clip1](https://user-images.githubusercontent.com/29240564/198215512-3e3773a0-9990-4a15-a374-4e15f341fd6c.png)

Here is a sample output

**Comment by uwejan** [comment]
Thank you @krayon007.
It does work with the compiled file `make linux ARCHID=6` but does not work with agent downloaded from server `interactive only`.
My take here is that all dependencies are available within the agent itself. Will it be possible to use files inside `moduels` directory as an SDK? How to solve the dependencies issue?
Anotehr idea on my mind is to create an electron.js app that deals with user interface but that will require me an SDK to interacte with the agent. I appreciate your input though.

**Comment by uwejan** [comment]
@krayon007 I appreciate what you have to say about me comment.

**Comment by krayon007** [comment]
What does it say when you run the agent downloaded from server? (How are you running it?)
Which files did you modify to test?

**Comment by uwejan** [comment]
Hey Brian, Like i said `interactive only ` downloaded from my server dose not do anything or output anything. while 
`./meshagent snippets/service-manager-test.js`
but the one i complided did exactly same output as you showed in screenshot above.
**What am really trying to do here**, is build an `electron.js` for the client. I'll need an SDK for that, and i think soem of the dependecies mentioned above are inside the client app itself, which is confusing me.

**Comment by krayon007** [comment]
Are you trying to run the downloaded binary over an SSH tunnel or something non-graphical? Normally that binary will try to display a dialog box. 

Are you trying to run your .js file with the downloaded interactive only binary? If so, try running it like this:

`./meshagent snippets/service-manager-test.js --no-embedded=1`

**Comment by uwejan** [comment]
Please answer me one question.
How can i use `/modules/*` as an SDK, so i can build totally independent app?

**Comment by uwejan** [comment]
I made a repo that shows what am trying to do.
https://github.com/uwejan/mc-ckient-ui/blob/3d3b8eeea1b8fb47e853e9af6c456f846b712c5b/src/App.vue#L12
My goal is to run this app stand-alone not to use the client binary for it. SoI am trying to use the `/modules/*` as an SDK.
I hope this clarifies what am trying to do.
![Screenshot-20221104001032-1157x319](https://user-images.githubusercontent.com/20250935/199834824-0fe6348f-6416-4277-9165-1cae13dd1ed4.png)

**Comment by krayon007** [comment]
I'm not sure I understand what your are doing. When you say run stand-alone without using the client binary, what does that mean? What is going to run the JavaScript? The client binary is what provides the JavaScript runtime environment...

**Comment by uwejan** [comment]
Offcourse the client binary is needed, my ui will depend on it, but in sense that its not required to run like this `./meshagent snippets/service-manager-test.js` .
Out of the box example, how you can integrate zoom API in any app using an SDK. But in this case am trying to build a UI app using vueJs, electronJs ..etc.
