### ISSUE TITLE
Not Able to find .msh file

### ISSUE THREAD

**Issue by prakash3113** [Ylianst/MeshAgent#158]
Hello, I have installed agent but not able to find .msh file in my windows device
i want to add my own meshcentral web server credentials, so how can i do that

**Comment by prakash3113** [comment]
After installing agent i am getting this info
![MeshCentral RAS Agent Details](https://user-images.githubusercontent.com/59164256/198513487-76ee1917-c9ec-4d26-8f35-acb8dde16ed9.png)

**Comment by krayon007** [comment]
The easiest way to get the .msh file, is if you go to your server, and in the url bar, add the query string `?debug=1` to the uri... Then if you refresh, you should be able to go to add agent, and there will be an option to just download the .msh configuration file.

**Comment by prakash3113** [comment]
> ?debug=1

Thanks for sharing 
i have cloned repo of agent and trying to build from visual studio 
after building while executing exe file it is showing error "No meshcentral settings found place .msh file"
can you help me whre i need to add .msh file?

**Comment by krayon007** [comment]
After you download the msh file from server, just name it the same as your executable, but with .msh instead of .exe

Just place the file in the same folder as the executable, and it should work.

**Comment by prakash3113** [comment]
> After you download the msh file from server, just name it the same as your executable, but with .msh instead of .exe
> 
> Just place the file in the same folder as the executable, and it should work.

Thanks its helped me alot😊😊
