### ISSUE TITLE
Problem: Kaspersky Endpoint Security for Windows detect meshagent as trojan/virus

### ISSUE THREAD

**Issue by senolkehya** [Ylianst/MeshAgent#18]
Hi Ylianst,
On my windows server 2012 r2 Kaspersky Endpoint Security for Windows installed. The antivirus software detects as a virus/trojan meshagent.exe and it delete the program executable.
As you know the antivirus softwares has different / similar algorithms for detection of the viruses on exes. Can you review the meshcentral.exe's assembly structure.
Maybe you can write to Kaspersky Labs for this issue.
Thanks

**Comment by senolkehya** [comment]
Also Panda Antivirüs detect meshagent.exe as trojan/virüs. Can you make an assembly challenge for meshagent.exe?

**Comment by webresurs** [comment]
Kaspersky SOS - detects during installation meshagent64...exe - PDM:Trojan.Win32.Generic

**Comment by si458** [comment]
nothing we can do because meshagent has been abused by bad actors im afraid
