### ISSUE TITLE
Set clipboard error

### ISSUE THREAD

**Issue by Hareesh15** [Ylianst/MeshAgent#192]
I tried packaging meshagent via innosetup and python executable, during that set clipboard option is throwing the below error in windows server 2016, windows server 2012 and windows 8.1, can you please guide us ?

Faulting application name: meshagent.exe, time stamp: 0x64b7d848
Faulting module name: ntdll.dll, version: 10.0.14393.5980, time stamp: 0x6459ba02
Exception code: 0xc0000374
Fault offset: 0x00000000000f7183
Faulting process id: 0x5cc
Faulting application start time: 0x01d9bc744fb8f87c
Faulting application path: C:\Program Files (x86)\MeshAgent\meshagent.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: a54a27d3-9376-4838-9b03-1a3a23b9242f
Faulting package full name: 
Faulting package-relative application ID: 

**---------------------**I am using the below python method to execute fullinstall command of meshagent** ------------------**

import subprocess
def run_powershell_command(command,timeout=600):
    command_output = subprocess.run(['powershell',command], stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
    return command_output

@si458 @Ylianst @ryanblenis @krayon007

**Comment by si458** [comment]
im sorry but i dont think this has anything to do with meshcentral or meshagent,
this must be something wrong with innosetup or your python exe
