### ISSUE TITLE
Meshagent don't work

### ISSUE THREAD

**Issue by LinkPhoenix** [Ylianst/MeshAgent#2]
Hello,

at home with a vm under debian mashagent.exe that I install on a Windows 10 it works very well. On the other hand, when I try this at work, it does not work. Lab is looklike my lab's home Server = Debian / Client = Windows 10 and on both Windows 10 firewall is enable

I have identified meshcmd.exe command-line syntax like: install / uninstall / fullinstall ....

I tried a lot of combinations and it does not work

in the MeshAgent.log log file I have the following line:

[2018-02-16 04:46:25 PM] FATAL EXCEPTION [MeshAgent_4483F3E81409D40B.exe] @ [FuncAddr: 0x5850290100000000]

**Comment by LinkPhoenix** [comment]
It's good I understood that I had forgotten.

In my office environment I had to adapt the following command:

node meshcentral --cert 1.2.3.4

since my client computer and my meshcentral server are not on the same networks so my client could not reach the server

**Comment by Ylianst** [comment]
Let me know if you still get this problem. The new MeshAgent will report a better exception error with a "delta" number that allows me to go in the code and see where the problem is.
