### ISSUE TITLE
ENH: Use Custom user-agent

### ISSUE THREAD

**Issue by ndragon798** [Ylianst/MeshAgent#200]
Hey just a enhancement request to use a custom user-agent for client connections instead of using a blank user-agent.
This is currently what the nginx logs look like when a client is checking in to the server
 `"GET /agent.ashx HTTP/1.1" 101 281 "-" "-" 170 251.379`
What it could look like with a custom user-agent
`"GET /agent.ashx HTTP/1.1" 101 281 "-" "MeshCentral Agent (Version: x.x.x.x)" 170 251.379`

**Comment by si458** [comment]
would showing it like this `MeshAgent 2024-Jan-28 00:45:00+0000` be ok?
its just basically saying MeshAgent and the commit-date which is what we use the `Current Core` identifier ?
ive been able to work out where to put the User-Agent in the `agentcore.c` !?
