### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by amanmuskan** [Ylianst/MeshAgent#207]
After taking the access, It is giving black screen and nothing is visible in client machine.

**Comment by smudge1977** [comment]
Does the client machine have a physical monitor attached?
What operating system is the remote?

**Comment by NiceGuyIT** [comment]
@amanmuskan You need to provide more information. Look at the information asked when opening a [new issue in MeshCentral](https://github.com/Ylianst/MeshCentral/issues/new/choose) and provide the same information.

**Comment by si458** [comment]
closing as stale, please reopen the issue in the correct repo https://github.com/Ylianst/MeshCentral
