### ISSUE TITLE
OS X Installer Fails Silently

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#22]
OS: OS X High Sierra
MeshCentral Version: 0.4.1-y and previous

If the extracted mpkg name contains a space (e.g. "MeshAgent 2.mpkg") the installer completes and appears to install successfully, except that it doesn't actually do anything. If you change the package name to "MeshAgent2.mpkg" and re-run it, it installs correctly. Probably an escaping issue in the install scripts somewhere.

**Comment by Ylianst** [comment]
The current MeshCentral has been using the name "MeshAgent.mpkg" for a long time. Is this bug still occurring? There is a [reference to is on Reddit](https://www.reddit.com/r/MeshCentral/comments/feuvan/improvement_suggestions/), but I not sure this is still a problem.

**Comment by ryanblenis** [comment]
The problem generally occurs when downloading an agent into the Downloads folder (browser default) where a file with that name already exists (like an older version, or me switching a machine from a local testing server to a live server), the file will download and extract as "MeshAgent 1.mpkg". The install fails completely silently, yet "appears" to have completed successfully according to the installer, others may be confused when their agent they just installed isn't showing up.

**Comment by krayon007** [comment]
Interesting. I'll take a look at it. I thought I used relative paths everywhere in the script, but I'll double check. Sounds like perhaps one of the copy commands failed.

**Comment by ryanblenis** [comment]
I believe this was fixed in a recent commit.
