### ISSUE TITLE
switch display/monitor on macos?

### ISSUE THREAD

**Issue by pwright225** [Ylianst/MeshAgent#230]
trying to change which monitor i am viewing on my mac and i cannot, went into preferences and set them all to clone and still couldn't get the app i needed on screen. 

is there a method i am missing? certainly i do not see the little monitor switching buttons where you can view all or one monitor at a time, like on windows.

**Comment by si458** [comment]
**!!! PLEASE FOLLOW THE BUG TEMPLATE REPORT !!!**

**Comment by si458** [comment]
i can replicate this, not sure why it doesnt detect the second screen?
sadly im not a C developer so i cant fix the issue but i will try my best to investigate for you

**Comment by si458** [comment]
the is already a request in the meshcentral about this issue, so cant do much at moment, so going to close
please follow https://github.com/Ylianst/MeshCentral/issues/3773 for updates
