### ISSUE TITLE
Expire devicesharing link on window close

### ISSUE THREAD

**Issue by kpetrow** [Ylianst/MeshAgent#236]
I use meshcntrl.js to generate a temp link and open it in an iframe.  Is there a setting to call --remove option on the session close?  Would it be best to call an unload event on sharing.handlebars?  Thanks

**Comment by si458** [comment]
you would have to handle all the removing of the links yourself manually.

**Comment by kpetrow** [comment]
just tossing out there that a duration of something like -1 would be awesome flag for remove on session close. Thanks, awesome software
