### ISSUE TITLE
No Terminal and Files Tab when I upload own version meshagent_x86-64

### ISSUE THREAD

**Issue by apexlee79** [Ylianst/MeshAgent#246]
Hello, 
I make some code changes in meshcore/agentcore.c and build a new version meshagent_x86-64 via "make -j8  linux ARCHID=6".
when i upload this new version meshagent_x86-64 bin file to replace MeshCentral/agents/meshagent_x86-64 .
but when I install this new meshagent on Ubuntu20/24 machines using  meshcentral web page : group ->"add agent" ->"linux/BSD" menu . 
after the Node is active, it does not have the Terminal and Files Tab, but if I swich back to previous MeshCentral/agents/meshagent_x86-64 version, it can show up Terminal and Files Tab.
any missing steps ?

thanks a lot !@

**Comment by apexlee79** [comment]
I restart the meshcentral service , the new version meshagent_x86-64 version works now.
if just replace meshagent_x86-64 file without meshcentral restart,  the terminal and files tab will not show for new adding Node.
looks like there are some cache in NodeJS web service, so cause this problem.
I will close this issue.

**Comment by si458** [comment]
Sorry for delay! 
Yes everything u changing something with meshcentral, 
Weather its a meshagent update, config change, or even add in gui improvements 
It's best to restart meshcentral
