### ISSUE TITLE
Update Supported TLS versions within the Install-Remotely.ps1 script

### ISSUE THREAD

**Issue by anedward01** [Ylianst/MeshAgent#248]
In the Install-Remotely.ps1 script, there is a hardcode to only support tls1.2 located at line 20:

`[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12`

My environment only supports tls1.3 connections which was causing the script to error out. To remedy this, I replaced line 20 with the following:

`[Net.ServicePointManager]::SecurityProtocol = "tls13, tls12"`

This allowed me to successfully download and install the application. It's not the best code, but it works well enough for what it serves.

**Comment by si458** [comment]
What `Install-Remotely.ps1` file?
We dont have that file?
Can u provide file/location of the file?

**Comment by anedward01** [comment]
Wrong Repository, my apologies
