### ISSUE TITLE
core files

### ISSUE THREAD

**Issue by Smiley-k** [Ylianst/MeshAgent#257]
Hi, I am observing a large number of 15 megabyte files of the following kind, which is taking up a lot of space on my PC, how can this be turned off ? 

![image](https://github.com/user-attachments/assets/b7d5b997-38ac-48c1-af30-b288b55ac026)

**Comment by si458** [comment]
i believe these might be crash core dump files,
so the meshagent is crashing/kernel panicing
have you checked your syslog/messages files for events?

**Comment by si458** [comment]
That is something u need to set in the OS, it's nothing to do with meshcentral or meshagent, u need to ask the OS to stop generating them, 
U can also check in ur config.json that use don't have the coredump enabled as meshagent will try to upload them files back to meshcentral for u to debug if it detects it crashed
