### ISSUE TITLE
Feature Request - OK/Cancel Message Window

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#26]
Hello,

Looking to see if there is any chance of getting an OK/Cancel type pop-up/alert with a callback that can be made available to the MeshCore?

The use case is fairly simple, I want to be able to interact with the user before performing an action, such as "Windows Updates have been applied to your PC, Click OK to Restart now, or Cancel to be reminded in an hour" or similar. 

Ideally the call would be able to pass the:
- Window Title
- Window Message
- OK Button Text
- Cancel Button Text
- Timeout before a default value is accepted

Thank you.

**Comment by krayon007** [comment]
That feature is actually already there. I wrote a module called message-box that basically does exactly that. I used it for the user consent dialog. If you look at how the dialog is popped on meshcore you can see how to use it. I can work on documenting it. I can't remember if I made it so you can rename the buttons, but all those other features are there.

**Comment by krayon007** [comment]
If you pull the agent repo, you can take a look at message-box.js in the module folders. I named the parameters in a descriptive fashion, so you'll see how to setup the dialog how you need.

**Comment by ryanblenis** [comment]
Awesome! Thanks - I'm going to look into that!
