### ISSUE TITLE
MeshCentral agent not launching on Windows 11 24H2

### ISSUE THREAD

**Issue by danyonline64** [Ylianst/MeshAgent#262]
Hello :) 
I recently updated to version 1.1.34 (docker). I’m not sure if it’s related, but when I download the agent on a freshly installed machine running Windows 11 24H2, the agent doesn’t open properly (a window briefly opens and closes immediately).

I noticed in the release notes that you mentioned new agents being tested. Could this be related?

Thank you in advance for your help! :)

Daniel

**Comment by si458** [comment]
We are going to explain this today at the community meeting at 2pm (UTC)!

The release includes test agents, inside `test_agents` which u need to copy into `agents` then restart ur meshcentral, let it resign etc then redownload the meshagent!

@Ylianst has done this because he doesn't want everyone's agents suddenly updating and then crashing or something happening!

I already discovered the 1.1.34 release broke windows 7 and server 2008 r2 ! And that wasn't even an agent update!

**Comment by danyonline64** [comment]
However, I don’t seem to have the /opt/meshcentral/MeshCentral/agents/test_agents directory in my setup. I suspect I might have made a mistake in my docker-compose :/ 

    volumes:
      - ./volumes/data:/opt/meshcentral/meshcentral-data
      - ./volumes/user_files:/opt/meshcentral/meshcentral-files
      - ./volumes/backup:/opt/meshcentral/meshcentral-backups
      - ./volumes/web:/opt/meshcentral/meshcentral-web

**Comment by si458** [comment]
@danyonline64 thats because its inside the container!
so you need to enter into the container first 
`docker exec -ti 'CONTAINER_NAME' sh`
or
`docker exec -ti 'CONTAINER_NAME' bash`

**Comment by danyonline64** [comment]
Thank you! I'm making progress thanks to you, I had never needed to dig into a container before! Here's where I am now:

![image](https://github.com/user-attachments/assets/04949764-e994-4b1b-8788-66f7fd0f2a38)

**Comment by si458** [comment]
sorry you shouldnt have the folder `MeshCentral` only the folder `meshcentral` inside `/opt/meshcentral/`
if you created `MeshCentral` delete it and only leave `meshcentral` as this folder has all the source code etc in
so it would be `/opt/meshcentral/meshcentral/agents/test_agents/`

**Comment by danyonline64** [comment]
Okay, it's fixed. In the meantime, I had modified my docker-compose, which caused the issue. Now I have the correct directories and I've found my agents!

![image](https://github.com/user-attachments/assets/e766f504-c769-40a0-bb53-0ced5099b261)

Thank you! Just to confirm, is the command I should now run ?

docker cp 'meshcentral':/opt/meshcentral/meshcentral/agents/test_agents 'meshcentral':/opt/meshcentral/meshcentral/agents

**Comment by si458** [comment]
Yes but the is only 5 agents inside `test_agents` so just copy those 5 agents
Then restart the container (DONT DOWN AND UP WITH DOCKER COMPOSE!)

**Comment by danyonline64** [comment]
It works!!! The Windows 64 agent has been successfully updated. I downloaded and launched it on my Windows 11 24H2 machine, and it works! Thank you so much for your help and patience!!! Merci !!!

**Comment by si458** [comment]
@danyonline64, no worries!
Please test as much as possible as next month we will move it, which means it will update all ur agents automatically!

**Comment by danyonline64** [comment]
@si458 ok !
