### ISSUE TITLE
New agent and Malwarebytes

### ISSUE THREAD

**Issue by danyonline64** [Ylianst/MeshAgent#264]
Hi :) 

It seems that Malwarebytes doesn’t like the new Windows agent—it systematically blocks it once installed. 

Is it just a matter of time before Malwarebytes accepts this new agent, as it did with the old one (which no longer works on the latest version of Windows 11)?

Thanks :)

**Comment by si458** [comment]
The old version does still work with windows 11, u just need to install the wmic before hand

Buy as for malwarebytes, nothing we can do keep submitting it to them saying its safe and see what happens
