### ISSUE TITLE
MeshAgent Installation Detected as Suspicious by Kaspersky

### ISSUE THREAD

**Issue by alireza-rou13** [Ylianst/MeshAgent#267]
Hello,
I encountered an issue with the MeshAgent installer. When downloading the file and scanning it with Kaspersky, no threats are detected. However, during installation, Kaspersky flags the application as suspicious.

Here are the details:

    Antivirus Software: Kaspersky Endpoint Security (12.7.0)
    MeshAgent Version: latest github and build it with visual studio
    Steps to Reproduce:
        Download the MeshAgent installer from mesh central.
        Scan it with Kaspersky (no issues detected).
        Start the installation process.
        Kaspersky flags it as suspicious and prevents installation.
[virustotal](https://www.virustotal.com/gui/file/f0289de4a77940ea98882029abdeb8b6b2229a449ba9ddc66bd7d50063d1cb86/detection)
![Screenshot 2024-12-09 113939](https://github.com/user-attachments/assets/94f4bad8-ca6c-42a1-85dc-8a397099a599)

**Comment by si458** [comment]
Unfortunately, there is nothing we can do about this

Bad actors abused meshcentral, and it's meshagent over the years (and even still doing it now, check recent YouTube videos)

So most antiviruses now marked the software as a virus or hacktool

The only thing I can recommend is the following:

1. Customise the agent as much as possible with name, logo, service, etc
2. purchase an EV code-signing certificate, this will let antiviruses know the software is ur and legit
3. Keep submitting to antivirus engines that infact it's not a virus and valid opensource software
4. If ur in a domain environment and control/look after the remote computers, then add the exe to the AVs allow list
