### ISSUE TITLE
MeshAgent http download issues

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#32]
Hi @krayon007,

Not sure if this is a bug or usage related. I'm attempting something relatively simple (download a file and save it to disk). I originally tried using the wget module you created, however I was getting extra data in the file that corrupted it. I had assumed this was due to the [wget](https://github.com/Ylianst/MeshAgent/blob/0ad37730c00a93632a72f933c61d7bd5a51b271c/modules/wget.js) module also piping _accumulator and _sha data.

So I used a couple straight http options like so:

```
var reqOptions = http.parseUri("https://assets.zabbix.com/downloads/4.4.4/zabbix_agent-4.4.4-windows-amd64-openssl.msi");
                    reqOptions.rejectUnauthorized = false;
                    var req = http.get(reqOptions);
                    req.on('error', function(e) { dbg('error' + e); });
                    req.on('abort', function() { dbg('abort'); });
                    var _file = fs.createWriteStream("zb.msi", { flags: 'w' });
                    req.on('response', function(resp) {
                        if (resp.statusCode != 200) {
                            dbg('rcode error');
                        }
                        resp.pipe(_file);
                    });
```

And the file (which is 6080kb) comes down at anywhere from 6081kb - 6102kb (random each time) and the msi is corrupt. The abort, error, and status code checks in the above code don't show anything.

Looking forward to any input you have on why this may be. I assume it's something I'm not understanding about the MeshAgent environment, but the code all seems fairly straightforward. 

As a bonus: removing the `reqOptions.rejectUnauthorized = false;` line produces no file. I had assumed that was checking SSL cert status, but nothing seems to happen at all if it is missing.

Thank you as always.

**Comment by krayon007** [comment]
I'll take a look at the wget thing... As for your sample, when you create the writestream, pass wb instead of w, so that the file gets opened for binary write. See if that makes a difference. I remember having similar issues with corrupt files if you try to write binary data to a file object that was opened in text mode.

**Comment by krayon007** [comment]
Also, the default for reject unauthorized is true. If you remove it, and no file is created, it means the server cert is not rooted in something the client trusts.

**Comment by ryanblenis** [comment]
Hi @krayon007,

Thanks, and apologies, I did actually start with a 'wb' mode, but was trying with just 'w' to see if that made a difference.

Not sure if anything jumps out at you, but the 'wb' mode adds 1-3kb of data to the size of the expected file (6081kb - 6084kb) in my tests. This is the same sizes I was seeing with wget, so I assume my assumptions about the additionally piped _accumulator and _sha data.

Thanks!

**Comment by krayon007** [comment]
Is that url you are fetching publicly accessible? (ie, I can write a test script to try and figure out what is going on)

**Comment by ryanblenis** [comment]
Yes it is. It's just a zabbix agent from the [Zabbix project](https://github.com/zabbix/zabbix)

**Comment by ryanblenis** [comment]
Just some additional info here for your testing. I tested several downloads and found the following:

- NO issue
-- 4MB JPG Test - https://upload.wikimedia.org/wikipedia/commons/1/1e/Caerte_van_Oostlant_4MB.jpg 
-- 5MB JPG Test - https://upload.wikimedia.org/wikipedia/commons/2/2d/Snake_River_%285mb%29.jpg 
-- 10MB JPG Test - https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg 
-- Putty - https://the.earth.li/~sgtatham/putty/0.73/w64/putty-64bit-0.73-installer.msi (3,094kb)
-- MongoDB - https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2012plus-4.2.2-signed.msi (262,575kb)

- Issue
-- Zabbix agent - https://assets.zabbix.com/downloads/4.4.4/zabbix_agent-4.4.4-windows-amd64-openssl.msi 
(6,080kb)
-- NodeJS - https://nodejs.org/dist/v12.14.1/node-v12.14.1-x86.msi (17,552kb)

*Issues* are off by ~1-4kb, and given that mongodb downloaded at ~260MB, I'm guessing it isn't a size issue. Maybe a bit of data in the file itself that is causing it?

**Comment by krayon007** [comment]
Thanks! I'm looking into it now...

**Comment by ryanblenis** [comment]
Awesome work! Thank you!
