### ISSUE TITLE
Cannot compile in Visual Studio

### ISSUE THREAD

**Issue by railsjack** [Ylianst/MeshAgent#36]
I was trying to compile MeshAgent, but failed.
Here is a screenshot on my side.
Please help me with this.

Thank you

![meshagent-error-screen](https://user-images.githubusercontent.com/1916657/74534743-60aaec80-4f6f-11ea-997e-f95a75de3313.png)

**Comment by krayon007** [comment]
Select debug or release. Looks like you selected debug_no_tls

I'll fix the build so notls works again, but for meshcentral usage, TLS is required.

**Comment by krayon007** [comment]
I fixed the build issue with the NO_OPENSSL build modes. I had added version information into process.versions, but forgot to add the tls checks to make sure OpenSSL was compiled in.

**Comment by railsjack** [comment]
Thank you for your fix!!!
I will check it right away.

**Comment by railsjack** [comment]
Thank you Bryan Roe. It works!
