### ISSUE TITLE
Is it allowed to rename as I like to? ex: "MeshAgent.exe" to "MeshApp" ?

### ISSUE THREAD

**Issue by railsjack** [Ylianst/MeshAgent#37]
If is allowed, then can you please let me know where to customize in the code?

**Comment by krayon007** [comment]
The binary name is not hardcoded anywhere in the code. The code will ask the OS for it's executable path. It will work fine with whatever you name it.

**Comment by railsjack** [comment]
I think that it is installed as always same name "MeshAgent.exe" in "C:\Profile Files\Mesh Agent" directory.
Not right?

**Comment by krayon007** [comment]
Oh, that's what you meant... I'm actually building a new installer, so i can make the binary name to use one of the command line parameters... I can add the ability to specify a custom installation path too...

**Comment by railsjack** [comment]
That's great idea! I will be going to wait it. How long will it take to
complete?
And, FYI, this is very interesting project for me as well. :)

**Comment by krayon007** [comment]
Its a holiday weekend, but I got most of it working already on windows and Linux. So probably early next week.

**Comment by krayon007** [comment]
This should be working with the current customization options.
