### ISSUE TITLE
Agent not connecting after OSX reboot

### ISSUE THREAD

**Issue by vicomte** [Ylianst/MeshAgent#39]
Working with OSX clients in Sierra, High Sierra, and Mojave; 

Starting up agent with working internet connects to meshcentral server and all systems are available from the server.

> [2020-02-19 08:58:45 AM] Attempting to connect to Server...
> [2020-02-19 08:58:45 AM] Connecting to: 659D7194E3A8BFF413ACFBF31C6BE5E73A825BE9AD6E8773F9E9C325CE46421F79DFA5A535D8050236FF91617823413A
> [2020-02-19 08:58:46 AM] Control Channel Connection Established...
> [2020-02-19 08:58:46 AM] TLS Server Cert matches Mesh Server Cert...

Disconnecting network, start meshagent...

> [2020-02-20 09:47:19 AM] Attempting to connect to Server...
> [2020-02-20 09:47:19 AM] Connecting to: 659D7194E3A8BFF413ACFBF31C6BE5E73A825BE9AD6E8773F9E9C325CE46421F79DFA5A535D8050236FF91617823413A

I reconnect network while in this state, but don't ever see further activity. I have a remote A/V rack at many remote facilities which reboots every night because that is the easiest way for us to have the system in a working state when the users start their day. If the network is not fully established by the time our OSX systems come online I get offline mesh clients that don't come back unless I reboot them manually or restart the service.

I'll have a peek through agentcore.c, but my C++ is a bit rusty so if anyone has some pointers I'd appreciate it. Thx.

**Comment by krayon007** [comment]
What server version are you running? That output looks to be from an older server, because I fixed an unrelated bug where it showed a hex string instead of the url, when it displayed the connecting to message.

**Comment by krayon007** [comment]
By the way, when you say internet is not available, do you mean internet connectivity, or network availability?  I'm guessing the latter? I say that because I have code for windows and Linux that registers for a system even when the network state changes, but I don't think I have code to do the same for freebsd or macos, which may explain your scenario.

**Comment by krayon007** [comment]
I'll take a look at this when I get back in the office. (Currently out sick). I have a few things to try and test, as  the retry algorithm shouldn't depend on network state, as I've done testing before where the nework stack was down, and it retried successfully when I brought the network stack up.

**Comment by vicomte** [comment]
Was 0.4.9-f, retrying with 0.4.9-k.

In my test case I am removing any Wifi/Ethernet connectivity altogether. I will try removing the upstream side

In my real-world case, the device would have an active ethernet connection, but it's upstream would possibly be offline. 

There are some objc/swift callbacks to notify about network change, but I'm guessing bridging them to c++ would be a heavy effort.

**Comment by vicomte** [comment]
Updating seems to have resolved my issues. Sorry, I thought I was current. 

I Will let it run a few cycles and see if that clears up my morning connections.

**Comment by vicomte** [comment]
Ok, circling around on this I am still seeing an issue. Using the 0.4.9-k from npm, across about 10 clients I get a random sampling of agents that do not connect successfully after a reboot. Still getting stuck at the "Connecting to: <HEX STRING> log line

I implemented a startup delay as OSX doesn't have defined ordering and that seemed to lessen the issue but not eliminate it. I am going to continue to increase the delay and see if any certain period eliminates the issue. I will also try to require networking before the plist will launch as well.

**Comment by krayon007** [comment]
Which version of MacOS are you using again? I just did a bunch of tests on Mojave, and I can't reproduce this issue. I even tried setting my ethernet adapter to inactive in the system settings, and the agent still periodically retries, and then successfully connects when I re-activate the interface.

When the interface is disabled, when it attempts to connect, it immediately fails with the message "Connection Error". Are you not seeing an error?

**Comment by vicomte** [comment]
Todays suspects where Sierra/High Sierra. I will make sure I have some Mojave in my pool going forward. 

The issues I was having with adapture up/down seemed to resolve after updating the server to -k. Today's are all a simple reboot with full connectivity otherwise.

**Comment by krayon007** [comment]
I have some ideas I can try to event when the network stack is ready, to see if I can prevent this situation...

**Comment by vicomte** [comment]
fwiw, with a 30 second delay, all my devices came online today.

**Comment by vicomte** [comment]
As an update, I have been tracking this up to 0.5.0-h and am still experiencing this. The startup delay i introduced does help, but hasn't eliminated our problem. Will update to 0.5.0-u and continue.

**Comment by vicomte** [comment]
0.5.3 now. Same activity. 

I have been browsing through the MicroStack code and isn't immediately apparent that there is a 'connect' timeout vs a 'idle' timeout for the websocket connection in these calls. Point me at TFM if i am blatently overlooking ;)

**Comment by vicomte** [comment]
0.5.68, all my devices have consistently been online every morning for 3 days so I am going to close this out.
