### ISSUE TITLE
Agent Debugging

### ISSUE THREAD

**Issue by ryanblenis** [Ylianst/MeshAgent#40]
Hi @krayon007,

Wondering if you can share some details on how MeshAgent / duktape debugging is done on the client side. Currently attempting to run this on a Mac.

Starting the agent from the command line yields:
``
Cannot setup debugger, missing promise and/or duktape-debugger
``

And I narrowed that down to 
``
duk_peval_string(ctx, "getJSModule('duktape-debugger');")
``

failing.

I've tried using this in conjunction with the `attachDebugger` call in the meshcore.js, and with duktape's duk --debugger but can't seem to get it working.

Being able to see console logging would be useful when developing plugins. Any other agent debugging would be helpful for tracking down this Mac Remote Desktop issue. Thank you as always!

**Comment by krayon007** [comment]
Pull the agent repo, and copy the duktape-debugger.js from the modules folder, and copy it into the folder where the agent binary is, then it should work. 
If you are doing this on a mac, use a browser other than safari, like Chrome.  I use a javascript command to scroll the window to the line of JS that is executing.. But for some reason this command doesn't work on Safari, which makes debugging a pain in the ass when using Safari.

**Comment by ryanblenis** [comment]
Thank you! I was missing it in the same dir as the agent.
