### ISSUE TITLE
Not updating Name of the computer?

### ISSUE THREAD

**Issue by killmasta93** [Ylianst/MeshAgent#41]
Hi,
I was wondering if someone else has had this issue before as i change the name of the computer but on the meshcentral it shows still the old name of the computer any  ideas?

![Screenshot from 2020-03-12 12-27-25](https://user-images.githubusercontent.com/13953629/76548734-37418b80-645d-11ea-8ecf-978a176c7ced.png)

![Screenshot from 2020-03-12 12-27-09](https://user-images.githubusercontent.com/13953629/76548751-3dd00300-645d-11ea-8fc7-01b36580b438.png)

**Comment by vicomte** [comment]
You can rename the device manually (helpful to me as my devices are named simple names in deployment but I tag them with a geographical name afterwards) , so I imagine that behaviour would stomp on this ability.
