### ISSUE TITLE
Unable to send CTRL+ALT+DEL to Server Core installs

### ISSUE THREAD

**Issue by nroach44** [Ylianst/MeshAgent#43]
I have the agent installed on Server 2012R2 and 2019 Core installs, and on other machines I'm able to use CTRL+ALT+DEL, but it doesn't work on Core.

Even if I set 
Disable or enable software Secure Attention Sequence (Set which software is allowed to generate the Secure Attention Sequence) = Enabled (Services)
via GPO, it still doesn't seem to work.

If I CTRL+ALT+DEL through other means, the rest of the session works fine. It's not limited to the login prompt though.

**Comment by krayon007** [comment]
From what I found on MSDN documentation, SAS.dll is not shipped with Windows Core. It says for Windows Server 2008, to copy the .dll from another windows system. Perhaps the same will work for Windows Core.
