### ISSUE TITLE
MacOS no mouse & keyboard control on login screen

### ISSUE THREAD

**Issue by philbot9** [Ylianst/MeshAgent#45]
I've noticed on MacOS 10.14 and 10.15, that I'm not able to control the mouse and keyboard from MeshCentral when on the login screen.

After installing the MeshAgent, connecting to it, and enabling the required permissions, I can control the keyboard and mouse as expected.
After the current user is logged out or the Mac is restarted, I'm able to connect and see the login screen in MeshCentral, however, I can no longer control the mouse or keyboard remotely.
Once the user logs in the keyboard and mouse start working again.

Is there something that can be done to fix this or is it expected behaviour?

Thank you.

**Comment by krayon007** [comment]
This is expected behavior. Starting with Mojave (or was it High Sierra, I can't remember), Apple changed the permissions, and made it so that the API I was using to inject remote input is blocked on the login process.

**Comment by philbot9** [comment]
Thank you for getting back to me.

Are there any plans to potentially resolve this or find a workaround?

I have tested with another (commercial) remote desktop solution and it does support remote input on the login screen. It also works with MacOS' built-in Remote Administration, which I believe uses VNC.

Thank you.

**Comment by krayon007** [comment]
For now, we have the vnc option in the UX to be able to connect to the agent using macOS's built in VNC server for the login screen.
