### ISSUE TITLE
Branding/Naming issues in agents installer

### ISSUE THREAD

**Issue by neroarth94** [Ylianst/MeshAgent#48]
I would like to ask about whether is it possible to change all the Mesh Agent names into something else? For example in Windows:

1. I would like to customize the installation path, instead of C:\Program Files\Mesh Agent\MeshAgent.exe, I would like to install it as C:\Program Files\<NAME_1>\<NAME_2>.exe
2. In the background process and services, instead of showing Mesh Agent Service and Mesh Agent background service, I would like to show it as <NAME_1> Agent Service and <NAME_1> Agent background service
3. In the installed application list, instead of showing MeshCentral Agent - Remote Control Software, I would like to show it as <NAME_1> Agent - Remote Control Software

This question is similar with issue #37 but it has no solution or info on how to achieve this. Is this kind of changes allowed and if it is allowed, can I know what changes do I need to do in order to achieve this?

**Comment by krayon007** [comment]
I added the ability to specify NAME_1 by using the --companyName="XXXX" from the command line when installing... I need to put in some additional work to support NAME_2, becuase that one requires some retooling with the self-update, because the service name was assumed to be fixed...

**Comment by krayon007** [comment]
The description is settable too, but I didn't yet create a command line switch for that... I'll add that in...

**Comment by nroach44** [comment]
@krayon007 I've tried installing the agent using .\meshagent64-%GROUP%.exe --companyname="Derp" -fullinstall (tried both - and -- for companyname) and it just ends up spitting out the switches on console. This is an agent installer from v62.

Is there another way of specifying the argument or is it linux only?

Cheers for the work!

**Comment by krayon007** [comment]
--companyName="Derp" is correct, however:
-fullinstall must be the first parameter.... The order of the rest of the -- switches is insignificant.

**Comment by krayon007** [comment]
So to clarify, you should be doing:
meshagent64-%GROUP%.exe -fullinstall --companyName="Derp"
