### ISSUE TITLE
Document meshagent.msh configuration

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshAgent#50]
I've been looking for a way to directly connect to the server instead of broadcasting... but couldn't find any documentation on the fact that I should change from `MeshServer=local` to `MeshServer=wss://server:443/agent.asx`

I had to do wild guesses by googling the issues and other messages.

Maybe I overlooked an obvious place to look for that part of documentation ?

I guess a dedicated README in the MeshAgent repo would help, for a start... or a Linux manpage maybe ?

**Comment by krayon007** [comment]
Currently, most the supported flags are listed in meshcore/agentCore.h, at the bottom of the file. Currently that only lists the additional flags that are supported, beyond the ones that the server usually sets... I'll add to it so it includes the ones the server sets... After I do that, I can move it to a readme or something, at the toplevel of the agent repo.

**Comment by jpele-tis** [comment]
Hello,
Please correct `MeshServer=wss://server:443/agent.asx` to `MeshServer=wss://server:443/agent.ashx`
