### ISSUE TITLE
MeshAgent Service Failed to Read Description. Error Code: 2

### ISSUE THREAD

**Issue by PaliPalo** [Ylianst/MeshAgent#51]
Hello, 

I got a big issue, the MeshAgent service on Windows won't start whatever I can do. 

As my LAN (and VPN) tests with the MeshCentral had reached a good satisfaction, I wanted to make test on Internet over our firewall. I then change the port of MeshCentral and use a domain name instead of an IP address.

So, I thought changing the installed agent with new .msh by installing it again with -fullinstall on some rogue workstations. 

And I felt on the case where the MeshAgent installation directory is empty and that the MeshAgent entry in the service manager displays "Failed to read description. Error code: 2" when selecting.

So I tried to make a cleanup install by deleting the service entry (`sc query 'Mesh Agent'` failed, but `sc delete 'Mesh Agent'` is ok) and the installation directory. Next, I launched the installation again. But that failed: the service does not start and show the same "Failed to read..." message and the installation directory is empty.

Uninstalling via the Windows application manager before reinstalling it, results to the same issues.
(I did not test an installation on a machine which never gets MeshAgent installed)

Today I updated the MeshCentral and tried installing a MeshAgent again from the binaries founds in the new MeshCentral. Result ? Still the same problem.

By keeping an eye on different folders to see what is copied and deleted, I can tell that the installation source executable is well copied in the installation directory, the service is created. But when it starts (I suppose) the installation directory is emptied and the installation source executable is deleted. But the service entry is still partially present.
(In the meantime I saw the same thing as the following issue https://github.com/Ylianst/MeshAgent/issues/49 )

I have no clue about what happened. Nothing in the events viewer. No log files.

How can I debug what happened ?

**Comment by PaliPalo** [comment]
I forgot the Windows versions I used.

Windows 10 Pro 64 btis. 1803 and 1909 for my current attempts

**Comment by krayon007** [comment]
When you ran the install again, what folder were you in when you ran it?

**Comment by PaliPalo** [comment]
I was on a specific folder. Either, the user Downloads folder or a new on created for this topic (eg. C:\MeshAgent)

**Comment by PaliPalo** [comment]
I just tried a dialog installation. Same issues.

**Comment by krayon007** [comment]
So you didn't try to run the agent installer from the install location? (ie: C:\Program Files\Mesh Agent)
When you ran the install, everything said it was  ok, like the following:

...Checking for previous installation [FOUND: C:\Program Files\Mesh Agent\MeshAgent.exe]
   -> Checking firewall rules for previous installation... [DELETED]
   -> Uninstalling previous installation... [DONE]
   -> Checking for secondary agent... [NONE]
...Installing service [DONE]
   -> Writing firewall rules for Mesh Agent Service... [DONE]
   -> Starting service... [OK]

**Comment by krayon007** [comment]
Can you check your virus scanner, to see if your virus scanner deleted it?
