### ISSUE TITLE
build failure with gcc 10

### ISSUE THREAD

**Issue by fefe17** [Ylianst/MeshAgent#52]
From the gcc 10.1 release notes:

GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking.

And indeed, "make linux ARCHID=5 -j8" fails with this linker error:

gcc -m32 microstack/ILibAsyncServerSocket.o microstack/ILibAsyncSocket.o microstack/ILibAsyncUDPSocket.o microstack/ILibParsers.o microstack/ILibMulticastSocket.o microstack/ILibRemoteLogging.o microstack/ILibWebClient.o microstack/ILibWebRTC.o microstack/ILibWebServer.o microstack/ILibCrypto.o microstack/ILibWrapperWebRTC.o microstack/ILibSimpleDataStore.o microstack/ILibProcessPipe.o microstack/ILibIPAddressMonitor.o microscript/duktape.o microscript/duk_module_duktape.o microscript/ILibDuktape_DuplexStream.o microscript/ILibDuktape_Helpers.o microscript/ILibDuktape_net.o microscript/ILibDuktape_ReadableStream.o microscript/ILibDuktape_WritableStream.o microscript/ILibDuktapeModSearch.o microscript/ILibDuktape_WebRTC.o microscript/ILibDuktape_SimpleDataStore.o microscript/ILibDuktape_GenericMarshal.o microscript/ILibDuktape_fs.o microscript/ILibDuktape_SHA256.o microscript/ILibduktape_EventEmitter.o microscript/ILibDuktape_EncryptionStream.o microscript/ILibDuktape_Polyfills.o microscript/ILibDuktape_Dgram.o microscript/ILibDuktape_ScriptContainer.o microscript/ILibDuktape_MemoryStream.o microscript/ILibDuktape_NetworkMonitor.o microscript/ILibDuktape_ChildProcess.o microscript/ILibDuktape_HttpStream.o microscript/ILibDuktape_Debugger.o microscript/ILibDuktape_CompressedStream.o meshcore/zlib/adler32.o meshcore/zlib/deflate.o meshcore/zlib/inffast.o meshcore/zlib/inflate.o meshcore/zlib/inftrees.o meshcore/zlib/trees.o meshcore/zlib/zutil.o meshcore/KVM/Linux/linux_kvm.o meshcore/KVM/Linux/linux_events.o meshcore/KVM/Linux/linux_tile.o meshcore/KVM/Linux/linux_compression.o meshcore/agentcore.o meshconsole/main.o meshcore/meshinfo.o -Lopenssl/libstatic/linux/x86 -l:lib-jpeg-turbo/linux/x86/libturbojpeg.a -L. -lpthread -ldl -lutil -lm -no-pie -lssl -lcrypto -lrt -z noexecstack -z relro -z now -o meshagent_x86
/usr/lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: meshcore/KVM/Linux/linux_events.o:/tmp/MeshAgent/meshcore/KVM/Linux/linux_events.h:37: multiple definition of `x11tst_exports'; meshcore/KVM/Linux/linux_kvm.o:/tmp/MeshAgent/meshcore/KVM/Linux/linux_events.h:37: first defined here
/usr/lib64/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: meshcore/agentcore.o:/tmp/MeshAgent/meshcore/KVM/Linux/linux_events.h:37: multiple definition of `x11tst_exports'; meshcore/KVM/Linux/linux_kvm.o:/tmp/MeshAgent/meshcore/KVM/Linux/linux_events.h:37: first defined here

The culprit is having not just type definitions but variable instantiations in include files, in this case in meshcore/KVM/Linux/linux_events.h:

```c
 37 x11tst_struct *x11tst_exports;
```

The regular fix would be to add extern here and then make sure the variable is instanciated somewhere. However, it turns out that nobody is referencing this in the release build, so just removing this line fixes the problem and saves a bit of memory, too.

**Comment by krayon007** [comment]
I fixed this issue, by adding the missing extern... That structure is used by the linux KVM to do remote input injection. It's used in meshcore/KVM/Linux/linux_events.c.

It's externed, because that value is set by the agent.
