### ISSUE TITLE
Provide the agent executable binaries in repository

### ISSUE THREAD

**Issue by damascene** [Ylianst/MeshAgent#54]
Few already reported MeshAgent being detected as a malware. It would really help if you provide the new agent with each update in binary executable format. With the executable in hand we can scan and send to our Antivirus vendor before upgrading the server and getting the software flagged and removed by antivirus software.

Plus: I had one interaction with support of the antivirus company and I sent them this repository link but they couldn't find the binary file. Maybe if it's provided this can make it easier for them to monitor it?

**Comment by krayon007** [comment]
The meshcentral repository already has the binaries. They are in the /agents folder.

**Comment by damascene** [comment]
> The meshcentral repository already has the binaries. They are in the /agents folder.

Any idea why no exe extension there?

**Comment by krayon007** [comment]
> > The meshcentral repository already has the binaries. They are in the /agents folder.
> 
> Any idea why no exe extension there?

If you aren't seeing any binaries, your antivirus probably deleted them? Here's a screenshot of the repo on Github.. You can see the .exe binaries are definitely there:

![agent](https://user-images.githubusercontent.com/29240564/85328140-070a7f80-b485-11ea-8e26-a34efeec7365.png)

**Comment by damascene** [comment]
Yes there are binaries but names confuesed me. which one is the one that got distributed to windows desktops? 
I found this one to be best match in name:
https://github.com/Ylianst/MeshCentral/blob/master/agents/meshagent_x86-64
is it this one:
https://github.com/Ylianst/MeshCentral/blob/master/agents/MeshService64.exe

**Comment by krayon007** [comment]
All the ones with .exe extensions are windows binaries.
meshagent_x86 is linux 32 bit for x86
meshagent_x86-64 is linux 64 bit for x86-64

**Comment by damascene** [comment]
Thank you for your response. I understand that MeshService64.exe and MeshService.exe are the meshagent.exe that are usually detected by some antivirus companies, right?
