### ISSUE TITLE
Clarify build instructions for libjpeg-turbo

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshAgent#55]
The repo seems to contain a copy of code in the lib-jpeg-turbo/ dev libraries, but the makefile instructs to recompile libjpeg-turbo-1.4.2...

I'm a bit puzzled, by what the proper process is, to rebuild the agents.

Also, what version of libjpeg-turbo is required ? In my Debian testing, I currently have libjpeg62-turbo-dev (1:1.5.2-2+b1)... whose version seems either to be 6.2 or 1.5.2... not 1.4.2, at least... 

Could you clarify ?

**Comment by krayon007** [comment]
Those instructions was just informational. I was just showing how I compiled it, using 1.4.2. The different configurations was because it was dependent on which headers you have installed on your platform. Jpeg 6.2 or Jpeg8, so I included instructions for how to compile for either.
