### ISSUE TITLE
Provide a way to dynamically link against OpenSSL, Crypto and other libs for Linux ?

### ISSUE THREAD

**Issue by olberger** [Ylianst/MeshAgent#56]
I kinda guess I see a rationale for statically linking to some libraries which may not be available on destination systems.

IIUC, the current status is that some libs are copied into this repo, and are embedded in a statically linked agent, even for Linux... 

However, security-wise, I wouldn't be pleased to have an agent running on my machine which includes potentially old libs, if MeshAgent wan't updated on the server, and when my system is up-to-date.

I kinda trust more my Debian updates, than my MeshCentral server's sysadmin's update policy.

I guess the next step, following my approach, would be to have a Debian package for MeshAgent, and only rely on the .msh file, and not install the agent's executable provided by the MeshCentral agent.

Maybe the use of obsolete libs doesn't put my system at risk, but given the power that the agent has over a system it's running on, I'd better trust that its libs are most up to date as possible.

Not to mention potential crypto flaws and likes, that may have slipped into the statically linked libraries, in case of a malicious build...

I'd probably prefer if the build system would use dynamically linked libs in this respect... but that'd lead to the need for many more builds I guess, if ABI changes happend between popular distros, etc.

Could you elaborate ?

Thanks in advance.

**Comment by Ylianst** [comment]
In general, we are pretty good at keeping up to date of the latest OpenSSL version, you can run the agent with --info to see the currently used OpenSSL version.

Bryan is testing the MeshAgent on over 20 different Linux virtual machines (maybe more at this point). The VM's span many different Linux distributions and versions including rather old Linux distributions. The first problem is that the more dependencies you have with OS components, the more testing you have to do and the more you have to deal with OS variations, so you need to compile more agent variants. We also have to make sure that each library correctly works with the rest of the MeshAgent code.

Another problem is that the agent is "paired" with the server version. So, the MeshCentral server does not have to deal with older agents except of course to update them. If you have the MeshAgent as a Debian package, you risk updating the server and rejecting all agent connections until agents are individually updated. Or worst, the agents get updated ahead of the server causing the server to get messages and see agent behaviors it was never designed for. Now you have to deal with agents and servers that could be of very different versions.

All this said, we are only 2 people working on MeshCentral mostly full time and we can't possibly do everything. The code is open and certainly welcome someone forking the code and attempting this. I am willing to guess that after a while, the resulting experience would be rather poor as agents would have to deal with various OS/Distro issues and version mismatch problems.

In the end, the agent is much more part of the server that deploys it, than it is part of the OS it's running on. So, the current system works really well. This said, feedback on this thinking is very much appreciated.

**Comment by olberger** [comment]
Thanks for the very detailed response. I can quite well imagine the mess of maintaining so many different combinations.

I hadn't thought a lot about the coupling issue betw. server and agent... I guess this is the biggest challenge.

The rest could probably be eased with more manpower/maintainers/contributors and automation (docker builds, and automated test envs... I've been thinking of Vagrant for ways to test azerty keyboard issues for instance... dunno if that relates to Brian's own VM setups)..

I may try and have a look at ways to create some Debian packages, to help base such discussion on more concrete case study.

Thanks again for your caring.
