### ISSUE TITLE
Build failure in VS 2019 - LNK2019	unresolved external symbol _crc32 referenced in function _deflate	MeshService

### ISSUE THREAD

**Issue by Jigar-PL** [Ylianst/MeshAgent#57]
![image](https://user-images.githubusercontent.com/13369193/86353358-bf55d600-bc84-11ea-96c6-a0d40da80dd1.png)

**Comment by krayon007** [comment]
Your build config is set to debug_notls
Change to either debug or release.
I'll fix the notls build, but keep in mind TLS is required for MeshCentral Server connectivity.

**Comment by Jigar-PL** [comment]
The same error occurred - I have already tried with other option also.

**Comment by krayon007** [comment]
That's wierd. I build with 2015 and 2017. That function is defined in ILibWebRTC.c

**Comment by Jigar-PL** [comment]
I have tried with VS 2019
![image](https://user-images.githubusercontent.com/13369193/86444559-883bff00-bd2e-11ea-9f0d-beb0a555446b.png)

**Comment by krayon007** [comment]
You sure you tried one of the configs that isn't "NoOpenSSL"? Because crc32 is defined in ILibWebRTC.c which is excluded if openssl support is not compiled in.

**Comment by Jigar-PL** [comment]
Thanks for the support, Now my build got successful. 
Error "TLS support disabled" fetch at time of connecting this new Agent with MeshCentral.

![image](https://user-images.githubusercontent.com/13369193/86511962-594f8700-be1b-11ea-9586-31279bca993c.png)

**Comment by krayon007** [comment]
TLS support is required to connect to the server.

**Comment by Jigar-PL** [comment]
Thanks for the update, Its work for me
