### ISSUE TITLE
64-bit EXE Issues: Desktop Session Connects w/ Black Screen & Unresponsive, Uninstall Does Not Remove C:\Program Files\Mesh Agent

### ISSUE THREAD

**Issue by jamesohareAll-In** [Ylianst/MeshAgent#58]
64-bit version allows Terminal connection (first attempt fails after "Setup..." but subsequent attempts connects as expected), but Desktop connection fails. The prompt is sent and when it is accepted the connection reports it is "Connected," however, the view is of a black screen and all actions (Wake up, Sleep, etc) have no effect.

Using -fulluninstall flag does not remove 'C:\Program Files\Mesh Agent' as well.

32-bit version seems to work (tested this with no prompt for user to accept).

**Comment by krayon007** [comment]
Which server version are you using?

**Comment by jamesohareAll-In** [comment]
For now, I'm just using the meshcentral.com server. MeshAgent is 0.2.1.

**Comment by krayon007** [comment]
The server version of MeshCentral.com is quite old, and needs to be updated, which we will do soon.

**Comment by jamesohareAll-In** [comment]
Okay, thank you for the update. If you could please comment on this issue
when the server has been updated, that would be very much appreciated.
Otherwise, I'll check back periodically.

Thanks,

James

**Comment by jamesohareAll-In** [comment]
This issue seems to have been resolved! Thank you very much for getting around to this so quickly. We really appreciate it!
