### ISSUE TITLE
MeshCentral Server  - Desktop/Terminals/Files tabs are not visible for new build in MeshAgent

### ISSUE THREAD

**Issue by Jigar-PL** [Ylianst/MeshAgent#59]
We build MeshAgent from your git (https://github.com/Ylianst/MeshAgent/tree/crashfix1)
And added it in your latest MeshCentral - master branch as Agent.

![image](https://user-images.githubusercontent.com/13369193/86515024-d0911500-be33-11ea-9a44-f66d925321cd.png)

![image](https://user-images.githubusercontent.com/13369193/86515059-09c98500-be34-11ea-9742-c009ff933b8b.png)

![image](https://user-images.githubusercontent.com/13369193/86515069-21087280-be34-11ea-96e1-5a25fd7cfc73.png)

**Comment by krayon007** [comment]
If you build from git, please build from master. That branch you built from is very old.

**Comment by Jigar-PL** [comment]
Thanks for the update, Its work for me
