### ISSUE TITLE
MIPS Compile Support

### ISSUE THREAD

**Issue by vanesvorld** [Ylianst/MeshAgent#6]
I am happy to see current support for MIPSel.

Are there any plans to support MIPS in the future?

**Comment by vanesvorld** [comment]
Yep: TP-Link Archer C5 V1, using the QCA9558 ver 1 rev 0 (MIPS 74Kc V5.0). 
file identifies meshagent_mips as LSB. 
OpenWRT & LEDE shoullld have toolchains (I used one for OpenWRT 18.06 recently but I can't locate that machine /sigh)

**Comment by krayon007** [comment]
The ddwrt tool chain we are using is big endian, and is for the Linksys WRT54G.

**Comment by vanesvorld** [comment]
Yeah, the issue is probably on my end. I’ll figure it out, thanks guys.

**Comment by vanesvorld** [comment]
With the new toolchain we forked and added ARCHID=8 for MIPS: `make linux ARCHID=8`
OpenSSL complains about the endianness: 

```
/../mips-buildroot-linux-uclibc/bin/ld: openssl/libstatic/linux/mips/libcrypto.a(blake2s.o): compiled for a little endian system and target is big endian
/../mips-buildroot-linux-uclibc/bin/ld: openssl/libstatic/linux/mips/libcrypto.a(blake2s.o): endianness incompatible with that of the selected emulation
/../mips-buildroot-linux-uclibc/bin/ld: failed to merge target specific data of file openssl/libstatic/linux/mips/libcrypto.a(blake2s.o)
/../mips-buildroot-linux-uclibc/bin/ld: not enough GOT space for local GOT entries
/../mips-buildroot-linux-uclibc/bin/ld: BFD (GNU Binutils) 2.29.1 internal error, aborting at elfxx-mips.c:10323 in _bfd_mips_elf_relocate_section

/../mips-buildroot-linux-uclibc/bin/ld: Please report this bug.

collect2: error: ld returned 1 exit status
makefile:341: recipe for target 'meshagent_mips' failed
make[1]: *** [meshagent_mips] Error 1
make[1]: Leaving directory '/home/sysop/devel/MeshAgent'
makefile:404: recipe for target 'linux' failed
make: *** [linux] Error 2
```
 
So we try to avoid openSSL for now with flag `NOTLS=1` and we get lots of undefined references:

```
/MeshAgent/meshcore/agentcore.c:2800: undefined reference to `X509_free'
collect2: error: ld returned 1 exit status
makefile:341: recipe for target 'meshagent_mips' failed
make[1]: *** [meshagent_mips] Error 1
make[1]: Leaving directory '/home/sysop/devel/MeshAgent'
makefile:404: recipe for target 'linux' failed
make: *** [linux] Error 2
``` 

What should we try next?

**Comment by vanesvorld** [comment]
Thanks Byran, 

We're using the toolchain generated by Buildroot 2019.02-git-00975-g9dcb5c581b with the following target flags: 

```
# Target options
#
BR2_SOFT_FLOAT=y
BR2_ARCH_HAS_MMU_MANDATORY=y
# BR2_arcle is not set
# BR2_arceb is not set
# BR2_arm is not set
# BR2_armeb is not set
# BR2_aarch64 is not set
# BR2_aarch64_be is not set
# BR2_csky is not set
# BR2_i386 is not set
# BR2_m68k is not set
# BR2_microblazeel is not set
# BR2_microblazebe is not set
BR2_mips=y
# BR2_mipsel is not set
# BR2_mips64 is not set
# BR2_mips64el is not set
# BR2_nios2 is not set
# BR2_or1k is not set
# BR2_powerpc is not set
# BR2_powerpc64 is not set
# BR2_powerpc64le is not set
# BR2_riscv is not set
# BR2_sh is not set
# BR2_sparc is not set
# BR2_sparc64 is not set
# BR2_x86_64 is not set
# BR2_xtensa is not set
BR2_ARCH_HAS_TOOLCHAIN_BUILDROOT=y
BR2_ARCH="mips"
BR2_ENDIAN="BIG"
BR2_GCC_TARGET_ARCH="mips32r2"
BR2_GCC_TARGET_ABI="32"
BR2_GCC_TARGET_NAN="legacy"
BR2_BINFMT_SUPPORTS_SHARED=y
BR2_READELF_ARCH_NAME="MIPS R3000"
BR2_BINFMT_ELF=y
BR2_MIPS_CPU_MIPS32R2=y
# BR2_mips_32 is not set
BR2_mips_32r2=y
# BR2_mips_32r5 is not set
# BR2_mips_32r6 is not set
# BR2_mips_interaptiv is not set
# BR2_mips_m5150 is not set
# BR2_mips_m6250 is not set
# BR2_mips_p5600 is not set
# BR2_mips_xburst is not set
BR2_MIPS_SOFT_FLOAT=y
BR2_MIPS_NAN_LEGACY=y
BR2_MIPS_OABI32=y
```
Here's a link to the full .config: [https://github.com/vanesvorld/MeshAgent/blob/master/br.config](url)

**Comment by krayon007** [comment]
ok, I fixed an unrelated issue when you set NOTLS=1, (missing include for limits.h and inttypes.h.

However, the reason you are seeing all those undefined references, is because you forgot to make clean before you tried to rebuild for NOTLS.... Your object files contain references to openssl, so if you try to build for NOTLS, without make clean, the compiler will complain, becuase it can't resolve those references, because NOTLS isn't linking OpenSSL anymore...

**Comment by vanesvorld** [comment]
Whoops, my oversight, nice catch.
After merge & make clean, error for `make linux ARCHID=8 NOTLS=1` was:

``
~/devel/buildroot/output/host/bin/mips-buildroot-linux-uclibc-gcc -DMESH_AGENTID=8 -std=gnu99 -g -Wall -D_POSIX -DMICROSTACK_PROXY   -fno-strict-aliasing -I. -Iopenssl/include -Imicrostack -Imicroscript -Imeshcore -Imeshconsole -DDUK_USE_DEBUGGER_SUPPORT -DDUK_USE_INTERRUPT_COUNTER -DDUK_USE_DEBUGGER_INSPECT -DDUK_USE_DEBUGGER_PAUSE_UNCAUGHT -DBADMATH -D_NOHECI -DMICROSTACK_NOTLS -Os -DNO_IPADDR_MONITOR -DNO_IFADDR -D_FORTIFY_SOURCE=2 -D_NOILIBSTACKDEBUG -D_NOFSWATCHER -Wformat -Wformat-security -fno-strict-aliasing   -c -o microstack/ILibParsers.o microstack/ILibParsers.c
In file included from microstack/ILibParsers.c:73:0:
microstack/ILibCrypto.h:100:10: fatal error: microstack/nossl/SHA.h: No such file or directory
 #include "microstack/nossl/SHA.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'microstack/ILibParsers.o' failed
make[1]: *** [microstack/ILibParsers.o] Error 1
make[1]: Leaving directory '/home/sysop/devel/MeshAgent'
makefile:404: recipe for target 'linux' failed
make: *** [linux] Error 2
``

Corrected by changing capitalization of SHA in microstack/ILibCrypto.h:100. 
NOTLS now builds, yay. I'd do a pull request, but I can't do it for just the one file (I've changed others on my fork).

**Comment by Ylianst** [comment]
Quick note to say that I have never tested the MeshCentral server with a "notls" agent. It will likely not work because the agent & server will try to compute a certificate hash on a null cert. We could make it work, but does not seem like something that should be supported.

**Comment by vanesvorld** [comment]
@Ylianst - Agreed & to be candid I have no desire to run **without** TLS. I figured building the NOTLS version might be a helpful debug-only step in the interim of investigating OpenSSL.

**Comment by Ylianst** [comment]
Totally makes sense, thanks. Any help & reports you can provide to make the agent better is very much appreciated.

**Comment by vanesvorld** [comment]
@krayon007 should I open a new issue for the OpenSSL endianness?
