### ISSUE TITLE
Communication: MeshAgent and MeshServer

### ISSUE THREAD

**Issue by sanjeevkumarsingh** [Ylianst/MeshAgent#63]
I am try to understand the communication between agent and server by debugging the agent code. Fresh built agent is not communicating to server and also find some difference in size.
I am building agent and placing a working .msh file.
Can you please help me to understand the same ?,any steps that i am ignoring, any document or anything relevant to it you can provide.
Sorry if my question is silly i am completely new in C and this area.

Thanks

**Comment by krayon007** [comment]
What messages are displayed on the screen when you start the agent in console mode?

**Comment by sanjeevkumarsingh** [comment]
Thanks for your help, It was SSL issue,i was using No_SSL, Now communication is working.
Any suggestion for me that can help me to understand communication code or logic?.

And thanks once again :-)

**Comment by Ylianst** [comment]
Take a look at section 8 of the [MeshCentral Design and Architecture document](http://info.meshcentral.com/downloads/MeshCentral2/MeshCentral2DesignArchitecture.pdf). You will see the details of how the agent connects to the server.
