### ISSUE TITLE
Opening Registry Key: Software\Open Source => Returned Error: 2

### ISSUE THREAD

**Issue by SuperGold910** [Ylianst/MeshAgent#68]
Hello, Developer.
Thank you for your effort to make this project.
I did download latest Meshagent source from here and compile it. But When I run MeshService64.exe and then click install button on UI, I can see "Opening Registry Key: Software\Open Source => Returned Error: 2" in console window.
I run  MeshService64.exe as administrator, but result is same. Strangely if I manually create HKEY_LOCAL_MACHINE\Software\Open Source on window registry, I can't see such error.
I can find such message in module\win-registry.js file, but I can't change it and debug it.
How to change and debug js source files ?
So I hope your kind help.

**Comment by krayon007** [comment]
I just fixed this issue... It has nothing to do with registry.js. It was the installer itself. I recently added support for customizing the service name, to support multiple installs. There are several use-cases where it needs to query the service name of any installed agents... There are multiple ways it tries to do this, one of them (the fallback case) is the registry... If no agents have ever been installed, this was throwing an exception, which is the exception you are seeing... I fixed this case... You'll need to re-pull the agent from the repository. 

This was a new feature that hasn't been released yet, so doesn't affect the agents that are deployed with the server. But this fix will be included in the next update.
