### ISSUE TITLE
MeshService64.exe no window only display a black  command windows then disappear

### ISSUE THREAD

**Issue by ahghygy** [Ylianst/MeshAgent#69]
I have downlaod mesh agent code，
buid by vs 2019
I choose release X64

It is succcessfuly build

but when i cllick the MeshService64.exe, thres is no windows to display, only a  a black  command windows  to show then disappear

So, anynoe can tell me how to show the the following window.
![image](https://user-images.githubusercontent.com/25763592/98913879-ef4e9900-2502-11eb-97f2-eb07eb852128.png)

![image](https://user-images.githubusercontent.com/25763592/98914249-62f0a600-2503-11eb-8bd4-347f7557c43c.png)

**Comment by krayon007** [comment]
Which commit did you pull? Commit ac8441cf3e76792a0ab08022a20bb93f07cf3205 (Nov 3) fixed a bug that caused that UI to crash on startup.

**Comment by ahghygy** [comment]
Ok thanks，I will have try it
