### ISSUE TITLE
How to debug javascript code on mesh agent service

### ISSUE THREAD

**Issue by ahghygy** [Ylianst/MeshAgent#70]
Hi guys,

I want to add breakpoint on java script code to debug Mesh agent services code.

I have a try to attach process to agent service, but fail.

1.So I want to know how to debug Javascript code on agent service?

2. The agent service how to get the HW information to send to agent central by java script, cloud you please give s sample?

![1](https://user-images.githubusercontent.com/25763592/99285800-fb27bb80-2872-11eb-9d1c-7f2383475fb0.png)

**Comment by ahghygy** [comment]
![image](https://user-images.githubusercontent.com/25763592/99285845-0d095e80-2873-11eb-8719-ab6ba61dd2c6.png)

**Comment by krayon007** [comment]
https://github.com/Ylianst/MeshAgent/issues/119
