### ISSUE TITLE
Please provide translated agents

### ISSUE THREAD

**Issue by Yvan-Masson** [Ylianst/MeshAgent#71]
Hi,

It would be great if the agent could be translated. Personally, I use MeshCentral to help people that are very concerned about privacy, so I need to use the interactive agent. However, many of them do not speak/read English at all, so even if we are talking by phone in the same time, they regularly find it difficult to launch the interactive agent.

Regards,
Yvan

**Comment by Ylianst** [comment]
Starting with MeshCentral v0.7.29, the agent is translated in 11 languages.

![MC2-AgentLanguages](https://user-images.githubusercontent.com/1319013/102680110-51d22f00-416a-11eb-8a54-3353c51bf5d7.png)

If you want to fix any translations, this file [has all the strings](https://raw.githubusercontent.com/Ylianst/MeshCentral/master/translate/translate.json). You can fix it and do a pull request on GitHub or [send it directly](https://www.meshcommander.com/contact-information). Lots of work from Bryan to make this happen.

**Comment by Yvan-Masson** [comment]
Thanks!
