### ISSUE TITLE
Linux interactive agent switch to show usage

### ISSUE THREAD

**Issue by Yvan-Masson** [Ylianst/MeshAgent#74]
Hi,

Would it be possible to add a switch to the Linux interactive agent to show usage, for example `-h`, `--help` or `-help`?

I tried all of these without luck. Currently the interactive agent has to fail (for example like #73) to reveal the `-connect` option.

Regards,
Yvan

**Comment by krayon007** [comment]
I added a `-help` switch... I verified it's live in v0.7.10

**Comment by krayon007** [comment]
It should show all available commands that are available with the configuration set by the server.

**Comment by Yvan-Masson** [comment]
I just checked, it works, thanks!
