### ISSUE TITLE
MeshService64.exe -exec  do not work

### ISSUE THREAD

**Issue by ahghygy** [Ylianst/MeshAgent#75]
Hi ,everyone,
I build agent 64 platform.
When I use the following command , it not work.
MeshService64.exe -exec "require('clipboard').nativeAddCompressedModule('agent-installer.js');process.exit();"
the code only go to the following code in ServiceMain.c file.
.....
CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
.........

then the command is always stuck there, there is no any respond.

So, How can I modify node js file then compress the js file into MeshService64.exe?

![image](https://user-images.githubusercontent.com/25763592/100629758-a00ec200-3364-11eb-9034-55b3ff4180c8.png)

**Comment by krayon007** [comment]
That command does not specify a js file, it specifies a module name. So do not include .js, only agent-installer.

**Comment by ahghygy** [comment]
Thanks krayon007，

The following is working now. but my 'xxxxxxxx' is not printout when I install MeshService64.exe.
Cloud you please tell me how make it work, I do not want copy js file into same folder with MeshService64.exe.
MeshService64.exe -exec "require('clipboard').nativeAddCompressedModule('agent-installer');process.exit();"

    if(process.platform == 'win32')
    {
        var loc = svc.appLocation();
        process.stdout.write(' xxxxxxxxxxx');
        process.stdout.write('   -> Writing firewall rules for ' + options.name + ' Service...');

**Comment by ahghygy** [comment]
It is working now. thanlks
I will close it
