### ISSUE TITLE
OS X Meshagent 98% CPU/battery usage

### ISSUE THREAD

**Issue by honestlai** [Ylianst/MeshAgent#76]
Hi,

Thank you for this project, what you guys have done here is amazing and awesome! I know your guys focus is more PC/Linux based, so I don't know how much work might go into this... but I installed mesh agent on a number of my home systems including my recently retired 2012 Macbook Pro. Because the battery life on it wasn't great, I never took it anywhere, but this last weekend I upgraded to one of the new M1 Macbook Air's. This thing is a beast!! Except the battery life was only getting about 1/3 of what was being advertised. Tonight I started digging into my system activity and noticed MeshAgent using 98% of my CPU... can that be right? I've been suffering from really random occasional freeze ups too, could this have been it?

<img width="955" alt="Screen Shot 2020-12-02 at 10 34 25 PM" src="https://user-images.githubusercontent.com/72324013/100987918-340e9400-34f3-11eb-9051-f738e5910bd2.png">

Anyways, I'll probably remove MeshAgent from my system for now to see if there's a difference, but wanted to see what you guys think, and also ask if there's any plans on an Apple Silicon version down the line?

Thanks!

**Comment by krayon007** [comment]
First things first, I actually already built an apple silicon version of the agent, we just haven't released it yet because my actual Apple Silicon Mac hasn't arrived yet, so I haven't tested it yet on actual silicon. If you still have the agent running, can you type `fdsnapshot` into the console tab, and report the results? That will show the open descriptors as well as it's state... That should help to determine why the CPU is pegged.

Attached is the universal binary I built, you can test that version as well to see if the issue is related to running the agent under Rosetta... Just unzip the file and you can run this agent. It's not live on the server yet, so it won't auto-update until it actually goes live.

[meshagent_osx-universal-64.zip](https://github.com/Ylianst/MeshAgent/files/5635038/meshagent_osx-universal-64.zip)

**Comment by krayon007** [comment]
I'll be able to do more testing with Apple Silicon once my hardware arrives.

**Comment by honestlai** [comment]
I restarted the agent, this is what the console shows:

> fdsnapshot
 FD[11] (R: 0, W: 0, E: 0) => MeshServer_ControlChannel
 FD[9] (R: 0, W: 0, E: 0) => Signal_Listener
 FD[15] (R: 0, W: 0, E: 0) => net.ipcServer
 FD[17] (R: 0, W: 0, E: 0) => ILibWebRTC_stun_listener_ipv4

Thank you for the binary, will try it out now

**Comment by krayon007** [comment]
Based on that descriptor table, the agent "should" be idle, as none of those descriptors are triggered. Is the CPU pegged currently?

**Comment by honestlai** [comment]
Unfortunately it looks like force quitting and restarting it temporarily fixed the issue. I'm going to let the intel binary keep running to see if the issue pops up again, and try to capture a snapshot then.

As for the universal binary... should I make it executable and put it in place of the current meshagent binary when I'm ready to test it out?

**Comment by krayon007** [comment]
> As for the universal binary... should I make it executable and put it in place of the current meshagent binary when I'm ready to test it out?

That would be the easiest way... 
`sudo launchctl stop meshagent`
then copy the universal binary on top of the old one, making sure it has the same name (and is executable)
`sudo launchctl start meshagent`

**Comment by honestlai** [comment]
Morning... I decided to install the agent on my wife's 2014 Macbook Air... it looks like meshagent is pegging her CPU on there also... altho it takes turns w/ her AV which has caused issues for me also : \

Below are some current snapshots while it's hitting the 80-95% usage range

<img width="1230" alt="Screen Shot 2020-12-09 at 9 25 47 AM" src="https://user-images.githubusercontent.com/72324013/101677390-99d1b300-3a00-11eb-95a3-c52908222e32.png">
<img width="754" alt="Screen Shot 2020-12-09 at 9 18 45 AM" src="https://user-images.githubusercontent.com/72324013/101677386-98a08600-3a00-11eb-9434-37d532198539.png">

Watching it, I notice it's not pegging as much as it was on my M1 Air, but it get's into the 90% range every 5-10 seconds or so. In general, while idle, and while in use, how much cpu and ram should Meshagent be taking up?

**Comment by krayon007** [comment]
![apple](https://user-images.githubusercontent.com/29240564/101695727-e1206980-3a29-11eb-94f7-62da85ee9e2f.png)

It shouldn't really use much at all, unless KVM is running... Here's the output of mine, running on an M1 mac mini. It's been running for a few days. This is also while I have terminal connected...

**Comment by honestlai** [comment]
Nope, no kvm... she just uses it to run dozens of browser tabs in 3 different browsers with tons of Office docs and zoom running all at the same time. Typical office work :P 

Took a peak this morning and it seems to be only using 0.1% cpu and memory. Guess it fixed itself... *shrugs*

**Comment by krayon007** [comment]
> Nope, no kvm... she just uses it to run dozens of browser tabs in 3 different browsers with tons of Office docs and zoom running all at the same time. Typical office work :P
> 
> Took a peak this morning and it seems to be only using 0.1% cpu and memory. Guess it fixed itself... _shrugs_

Well last night we updated the macOS agents to fix in interoperability issue with older versions of macOS (10.13 and older), so your agent probably restarted... However, this version of the agent, I added some more instrumentation... So if you notice the CPUi going to 100% again, from the console tab, you can type `timerinfo`. This will show all the pending timers. Hopefully this will reveal the cause, as there are only a handful of ways I can see the agent consuming 100% cpu on the main thread.

1. One of the descriptors is triggered, without being serviced. (Which we ruled out already, based on your results)
2. The select() timeout is set to 0. (In this version of the agent, `fdsnapshot` will show what the current timeout is
3. One or more timers was set with a 0 timeout. This will show itself in the `timerinfo` command as well as the above command
4. The executing JS resulted in an infinite busy loop. (This is most likely ruled out as well, as if this happens, the agent will not be responsive, becuase it will starve the main thread)

**Comment by Ylianst** [comment]
Bryan found a fixed a situation where the agent would loop and use up the CPU on all platforms. We are testing the agent now, should be out soon. Hopefully it will fix this issue.

**Comment by honestlai** [comment]
Terrific, thank you
What do you folks think if the Solarwinds breach? I work for a small MSSP that has a dozen more so clients (some medium to large) that we’ve used Solarwinds with for years... we’ve been looking for reasons to drop them because of how messy their billing has been lately, turns out it wasn’t just their billing that was messy.

**Comment by Ylianst** [comment]
Ha. Like hopefully everyone else, I am very concerned about software security and privacy. I certainly would like to run my own personal cloud for many of the services I need, but it's difficult to control the entire stack from hardware to network connectivity to software. If there is anything I can do or recommendations people have for increased security that would apply to MeshCentral, I am very much interested.

**Comment by honestlai** [comment]
I was considering suggesting this platform to my boss for our multi-tenant needs. The RMM we’re moving our clients over to does not have multi-tenant capability.
After playing around with the docker installation I’ve been running, I thought of found a few suggestions / feature requests that I think would be extremely helpful from a security standpoint.
The two primary things would be giving the administrator(s) the ability to turn on/off other users 2FA along with making it a requirement.
A second feature that I think would be game changing security wise would be having the ability to do IP filtering, and making the IP list accessible both thru the GUI and through the command line in case the admin’s home dynamic up changes and they get locked out.

**Comment by honestlai** [comment]
I found in the documentation how to do IP filtering  for the webgui... that's really awesome that you guys thought of it.

**Comment by krayon007** [comment]
If you continue to see CPU utilization issues, please re-open this issue.
