### ISSUE TITLE
Install as Local System account

### ISSUE THREAD

**Issue by githubbiswb** [Ylianst/MeshAgent#77]
We have many windows 10 VMs  that people RDP into we need to use mesh central with and the mesh agent to do maintenance and also do Mesh Router to them as well. We use the following process to install them as a Local System account so that we can interact with the remote desktop session when someone is connected:

• Download PsTools from https://download.sysinternals.com/files/PSTools.zip ( I have a copy in my Utility folder)
• Unzip the content and copy PsExec.exe to C:\Temp (or whatever folder we use)
• Open a Command Prompt as admin
• Run the command
	• cd c:\Temp\PSTools\
• Run the command
	• psexec.exe -s -i cmd.exe
• In the new window that spawns run the command
	• cd c:\Temp
	• Meshagent64-xxx.exe
• Run the Install/Update option
Exit all windows

This process has worked quite well in the past, but I just tried this evening with a new VM we are standing up, and after I hit Install, it just hangs and shows a window I can't do anything with. 

Thankfully I still had an old copy of the agent around and that one worked as expected. It also then updated to the latest version as expected and without issue. 

My current MeshCentral server version is 0.6.98 but I don't recall what the version was of the old agent. 

I also still have both agents and can get you version info on the agents if someone can let me know how to do that. I can get it out of the connected one, but I am not sure about how to do it with the old one. 

These are also VMs I can spin up and down so if anyone needs to see it or whatever, I would be happy to spin one up.

**Comment by krayon007** [comment]
Is there a reason you need to run psexec to install the agent? If you open an elevated command prompt, and run the agent installer, it will install as LocalSystem already.

**Comment by krayon007** [comment]
You can try to install the agent from the command line, using the `-fullinstall` command line switch... I have a feeling that running it normally won't work from LocalSystem, becuase it will try to launch a dialog box, which normally you cant do from LocalSystem.

**Comment by krayon007** [comment]
Also, if you specify the `-info` command line switc, it will spit out all the version information, including the commit hash the agent was built from.

**Comment by githubbiswb** [comment]
> 
> 
> Is there a reason you need to run psexec to install the agent? If you open an elevated command prompt, and run the agent installer, it will install as LocalSystem already.

I don't have a specific reason other than our goal is to allow someone to share their RDP session, and I found this way of doing it. As long as the result is the same after I do it this way, I would happily change to doing it that way as it would be easier for sure. I will attempt it and report my results along with agent hashs.

**Comment by githubbiswb** [comment]
I had the same issue when running as just administrator, and it looks to be the Windows Smart Screen filter. With that said, the -fullinstall option worked great, so than you for that tip and now I don't need PSTools either so that is a win. Any anyone wanting to install as a local service would likely know how to do the command line switches, or it wouldn't be hard for them to implement. 

For completeness, agent info output below

Old Agent that worked every time - Compiled on: 13:06:42, Mar 15 2019
New Agent that I can't get to the dialog box with -  Commit Date: 2020-Nov-17 23:47:29-0800

My new full install for those seeing this from google

* Open Command Prompt as Administrator
* Cd to the directory you have the meshagent installer stored
* Run the command:
  - meshagent.exe -fullinstall

Thank you for all of the assistance, and I will mark this as closed
