### ISSUE TITLE
Syntax error meshagent OpenWRT install

### ISSUE THREAD

**Issue by VM-2020** [Ylianst/MeshAgent#78]
Hi,.. got the following output after downloading and installing.

chmod 755 meshagent
./meshagent
./meshagent: line 1: syntax error: unexpected "("

**Comment by krayon007** [comment]
So you are saying when you do:
`chmod 755 meshagent` is succeeds, 
but when you follow it up with: 
`./meshagent`
you get the syntax error?

What device are you running this on?

**Comment by VM-2020** [comment]
Hi, yes.. we're trying this on GL.iNet AR750.

We're also looking at MV1000 from GL.iNet but this device has a ARM cpu.

**Comment by krayon007** [comment]
Which download option did you use?

**Comment by VM-2020** [comment]
The Linux/BSD/MacOs Binary installer > Linux MIPS24KC (OpenWRT)..

**Comment by krayon007** [comment]
What were the steps you did to get the file to your device? I just downloaded the OpenWRT binary installer, and tested it on my AR750, and it worked successfully/

![24kc](https://user-images.githubusercontent.com/29240564/101937245-76d90780-3b96-11eb-9146-55d2e5005287.png)

**Comment by VM-2020** [comment]
/mnt/MICROSD # wget -O meshagent --no-check-certificate "https://.................&meshinstall=28"
/mnt/MICROSD # chmod 755 meshagent
/mnt/MICROSD # ./meshagent

**Comment by krayon007** [comment]
OK, I tried doing the wget method too, and am still unable to reproduce this issue on my AR750... Can you zip your binary you downloaded and privately email it to me? (my emaill address is in my profile)

**Comment by VM-2020** [comment]
Trying to get the AR750 back (colleague is doing some WireGuard setup) - so couldn't do anything yet but did pickup the MV1000 with ARM cpu. Looks if this device has the same issue but also could be the same mentioned like issue #80.

**Comment by krayon007** [comment]
> Trying to get the AR750 back (colleague is doing some WireGuard setup) - so couldn't do anything yet but did pickup the MV1000 with ARM cpu. Looks if this device has the same issue but also could be the same mentioned like issue #80.

For the MV1000, you'll need this version of the agent, which was compiled for OpenWRT with that SoC... This is the build that will go live with the next update...

[meshagent_aarch64-cortex-a53.zip](https://github.com/Ylianst/MeshAgent/files/5832272/meshagent_aarch64-cortex-a53.zip)

**Comment by DVRSOLUTIONS** [comment]
Hey, works out of the box.. thanks!
