### ISSUE TITLE
Microsoft Windows XP Professional version 2002 Server Pack2 Failed to install agent

### ISSUE THREAD

**Issue by lingf1302** [Ylianst/MeshAgent#79]
When I installed the 32-bit agent on Microsoft Windows XP Professional Version 2002 Server Pack2, I was prompted that meshagent32.exe was not a valid Win32 application.
I would like to know if the current 0.7.24 version still supports the Windows XP32-bit operating system.

**Comment by krayon007** [comment]
Currently the minimum supported system is Windows 7 SP1. XP support is not possible because of necessary features that are missing in XP.

**Comment by lingf1302** [comment]
Ok, Got it.Thank you very much for your reply.
