### ISSUE TITLE
Linux ARM -HF

### ISSUE THREAD

**Issue by 1001crew** [Ylianst/MeshAgent#81]
Hi
in my server list of mesh agents '/meshagents' there are 2 same description Linux ARM - HF respectively #25 and #27.

Anybody know what is the difference (apart the size) ?

Thanks
Paolo

**Comment by krayon007** [comment]
27 does not have KVM support.

**Comment by 1001crew** [comment]
Noted with thanks.

Can I suggest to add 'noKVM' to the title ?
Same as done for #19 & #20 

Thanks

PS: Happy New Year
