### ISSUE TITLE
Which ports

### ISSUE THREAD

**Issue by 1001crew** [Ylianst/MeshAgent#82]
Happy New Year !!!

Sorry if this is a FAQ

Which port meshagent open (outgoing) to connect to the main server ?

I need to exclude these ports from the VPN connection otherwise it is lagging...

Thanks

**Comment by krayon007** [comment]
Currently the agent does not use a fixed port number for outbound connections.

**Comment by krayon007** [comment]
Unless you are referring to destination port, in which case by default it's 443 unless specified otherwise by your server.

**Comment by 1001crew** [comment]
> Currently the agent does not use a fixed port number for outbound connections.

Okay. Is there a way to have outbound connection fixed to a specific port ?
Thanks

**Comment by krayon007** [comment]
I can do some experiments with setting a configuration flag. The main caveat tho is that the agent uses multiple outbound connections, as the tunnels and control channel are separate.

**Comment by 1001crew** [comment]
appreciate if you can do test and let me know which ports you have been able to set.
Thanks + let me know
