### ISSUE TITLE
clickjacking 

### ISSUE THREAD

**Issue by yuling3086** [Ylianst/MeshAgent#83]
Hi,

Currently we do a vulnerabilities scan and we face the following issues.The below 2 ports is meshcentral :

The following pages do not use a clickjacking mitigation response header and contain a clickable event :

- https://xxxxx.com:31443/

- https://xxxxx.com:31443/terms

May I know for the below issues how can we fix it?

**Comment by krayon007** [comment]
This is a duplicate of: https://github.com/Ylianst/MeshCentral/issues/2180
