### ISSUE TITLE
install the locked powershell mesh agent

### ISSUE THREAD

**Issue by s-monzon** [Ylianst/MeshAgent#86]
Hello, I am trying to deploy the installation of meshcentral agent in my institution on windows platform, but we have difficulties, being that by security policies powershell is blocked and the deployment by gpo does not support extensions .exe, what would be the solution.

I analyzed the source code of the mesh agent and observed that the js files call powershell.

Thank you very much
![Captura](https://user-images.githubusercontent.com/81771517/113334806-83769c80-92fa-11eb-9597-481b9388c4c4.JPG)

**Comment by krayon007** [comment]
Powershell is only used by the installer on some versions of windows to update the firewall settings... I'll test modify the installer to ignore errors in that case instead of failing...

**Comment by s-monzon** [comment]
Downloading and starting to compile agent.
Thank you very much

**Comment by s-monzon** [comment]
![image](https://user-images.githubusercontent.com/81771517/119595944-bbf39d80-bdb4-11eb-930b-a6c470ce7f85.png)

**Comment by s-monzon** [comment]
good evening, after trying several times and making different modifications, I still have the same problem.
I can't find a way to skip Powershell.
Since in my organization the use of PowerShell is blocked, it is not possible for me to install the agent.

Thank you very much for your help.

**Comment by krayon007** [comment]
That's wierd, the latest changes to the installer should already be there.... On a side note, is your access to powershell only blocked for logged in users, or is it also blocked for LocalSystem? I'll check the installer again.

**Comment by s-monzon** [comment]
As per your query we did all the checks, but we cannot enable PS, since we have it blocked in registered users and localsystem, this totally prevents the use of PS. 
We have it blocked in registered users and localsystem, this totally prevents the use of PS.
This configuration is set GPO on computers joined to the domain and is based on security policies that we must established by the staff of Information Security.

Thank you very much for your help.

**Comment by s-monzon** [comment]
continuando con el asunto, que configuraciones de firewall son las que modifica el agente, dado que si puedo encontrar la forma de modificarlas de otra manera, no debería fallar el instalador.

Saludos

**Comment by s-monzon** [comment]
the powershel problem, it was concluded everything works perfectly
