### ISSUE TITLE
Mesh Agent state incorrectly returns "Not installed"

### ISSUE THREAD

**Issue by jpele-tis** [Ylianst/MeshAgent#87]
Hello there,

Everything is actually working correctly on our side, but our Mesh Agent returns an incorrect status :

```
_meshagent.exe state
Not installed
```

Good to know : we used all arguments of `agentCustomization` in the `meshcentral-data/config.json`

```
      "agentCustomization": {
        "displayName": "Mesh Company™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Company",
        "serviceName": "companymeshagent",
        "fileName": "company_meshagent"
      }
```

![image](https://user-images.githubusercontent.com/57767497/115251042-6fb89c00-a12a-11eb-8bd2-8df1db085219.png)

**Comment by krayon007** [comment]
Oh thanks for pointing that out! That particular command was never updated when customization support was added. I will fix that in the next agent update.

**Comment by jpele-tis** [comment]
> Oh thanks for pointing that out! That particular command was never updated when customization support was added. I will fix that in the next agent update.

Thanks a lot

**Comment by krayon007** [comment]
This looks to have been resolved quite a while ago... If you are still having issues with this, please feel free to reopen.

**Comment by jpele-tis** [comment]
Hello,
So I've tested it out by updating my TEST and PROD server, and the result is that on my PROD server the returncode is always 0.
On my TEST server the returncode is correct as described here : https://github.com/Ylianst/MeshAgent/blob/master/meshservice/ServiceMain.c#L339

Since agent version is always 0.2.1.3 I cannot tell you wish one is on a newer version.


PROD server :
`run('"%s" %s' % (app_path, "state"), accept_returncodes=[0, 1, 2, 3, 4, 5, 6, 7, 100])
<RunOuput returncode :0>
'STOPPED\n0\r\r\n'
run('"%s" %s' % (app_path, "state"), accept_returncodes=[0, 1, 2, 3, 4, 5, 6, 7, 100])
<RunOuput returncode :0>
'RUNNING\n0\r\r\n'`

TEST server :
`run('"%s" %s' % (app_path, "state"), accept_returncodes=[0, 1, 2, 3, 4, 5, 6, 7, 100])
<RunOuput returncode :4>
'Running'
run('"%s" %s' % (app_path, "state"), accept_returncodes=[0, 1, 2, 3, 4, 5, 6, 7, 100])
<RunOuput returncode :1>
'Stopped'`

**Comment by krayon007** [comment]
To get the agent version run the following command from where the agent is installed:
`MeshAgent -info`

Another command to try from where the agent is installed:
`MeshAgent -name`

I'm curious of the second command returns the correct service name.

**Comment by jpele-tis** [comment]
PROD server :
```Compiled on: 13:53:32, Feb 12 2022
   Commit Hash: 7df445ac6db21928b00649831a986e2e39c5259a
   Commit Date: 2022-Feb-11 23:39:43-0800
Using OpenSSL 1.1.1l  24 Aug 2021
Agent ARCHID: 4
Detected OS: Microsoft Windows 10 Professionnel - 21H1/19043 - x64
0

xxxxxxxxmeshagent.exe -name
xxxxxxxxmeshagent
0

```
(There is a random 0 on the prints)

TEST server :
```
Compiled on: 17:18:29, Mar 25 2021
   Commit Hash: 6c36f2fa6b5920ea73eb9ef478647b2277dec888
   Commit Date: 2021-Mar-25 16:58:15-0700
Using OpenSSL 1.1.1k  25 Mar 2021

MeshAgent -name
Mesh Agent

```

**Comment by krayon007** [comment]
Are your Test and Prod server configured the same? It looks like the service name is different between your two environments.

**Comment by jpele-tis** [comment]
@krayon007 any news ?

**Comment by krayon007** [comment]
On your machine that is reporting "Not Installed", can you run the following command, using your agent binary, substituting MeshAgent, with whatever your binary name is:

`MeshAgent -exec "console.log(_MSH().meshServiceName);process.exit();"`

And then on the same machine, open the following registry key, and check to see if the name returned from the previous command, is contained in the following reg key. If the previous command returned undefined/null, then assume the service name is `Mesh Agent` when checking the registry key.

`HKEY_LOCAL_MACHINE\SOFTWARE\Open Source`

**Comment by jpele-tis** [comment]
Hello,
```
run(f'"{app_path}" -exec "console.log(_MSH().meshServiceName);process.exit();"')
<RunOuput returncode :0>
'undefined\n'
```

Everything looks fine now:
```
run('"%s" %s' % (app_path, "state"), accept_returncodes=[0, 1, 2, 3, 4, 5, 6, 7, 100])
<RunOuput returncode :0>
'RUNNING\n'
```

 can you confirm me that you no longer plan to use different return_code corresponding to:
```
    // SERVICE_STOPPED				  1    The service is not running.
    // SERVICE_START_PENDING		  2    The service is starting.
    // SERVICE_STOP_PENDING			  3    The service is stopping.
    // SERVICE_RUNNING				  4    The service is running.
    // SERVICE_CONTINUE_PENDING		  5    The service continue is pending.
    // SERVICE_PAUSE_PENDING		  6    The service pause is pending.
    // SERVICE_PAUSED				  7    The service is paused.
    // SERVICE_NOT_INSTALLED		100    The service is not installed.
```
And now always return 0 ?

**Comment by krayon007** [comment]
Yes, some of those command line arguments were modified so that they are now handled in JavaScript instead of native, because the native implementation was incomplete, and the functionality was already implemented in JS. I was trying to make the behavior consistent between the different platforms, which is why it returns 0. If you need the return code to match the value from the Windows Service Manager, I can look into creating a different windows specific command line argument to do that?

**Comment by jpele-tis** [comment]
It's good for me you can close, the issue, thanks for you past actions
