### ISSUE TITLE
Question: Is MeshAgent able to allow multiple different installations co-existing with each other?

### ISSUE THREAD

**Issue by neroarth94** [Ylianst/MeshAgent#88]
For example, I have a MeshCentral 1 and MeshCentral 2 in two different server.
The client PC would sometimes connect to MeshCentral 1 and sometimes connect to MeshCentral 2.
Currently, if i install the agent provided by MeshCentral 1, the previous agent provided by MeshCentral 2 is uninstalled.
Anyway to let them co-exist together in Windows?

**Comment by vitko-bg** [comment]
Have you tried to use agent customization on one of the MC2 servers? Please try and report back. It should work fine

**Comment by neroarth94** [comment]
Umm sorry, where is the agent customization?

**Comment by vitko-bg** [comment]
Try to add this to your domain section in config on one of the MC2 servers

"agentCustomization": {
        "displayName": "Compagny® Product™",
        "description": "Compagny® Product™ agent for remote monitoring, management and assistance.",
        "companyName": "Compagny",
        "serviceName": "compagnyagent",
        "fileName": "compagnyagent"
      },

**Comment by neroarth94** [comment]
I have tried updating the agentCustomization in meshcentral-config-schema.json and restarted MC but nothing is changed
![image](https://user-images.githubusercontent.com/59238910/116639093-46a1d200-a99a-11eb-9941-8ebe2fb3261a.png)

**Comment by krayon007** [comment]
> I have tried updating the agentCustomization in meshcentral-config-schema.json and restarted MC but nothing is changed
> ![image](https://user-images.githubusercontent.com/59238910/116639093-46a1d200-a99a-11eb-9941-8ebe2fb3261a.png)

Did you reinstall the agent after making that change? That change only affects new installations, not existing ones.

**Comment by neroarth94** [comment]
Yes i did reinstall the agent. I have found the problem, sorry I forgot to delete auto generated meshcentral-data folder.
After deleting the folder, configuring the sample-config.json and restarting meshcentral, the new mesh agent now displays the name as desired. Thank you~
