### ISSUE TITLE
how to build agent？

### ISSUE THREAD

**Issue by gouchaoer** [Ylianst/MeshAgent#95]
i try to build the agent, but the environment is so difficult.  Is there a dockerfile to build the agent?
thanks!

**Comment by krayon007** [comment]
Which OS are you trying to compile for?

**Comment by gouchaoer** [comment]
> Which OS are you trying to compile for?

I'm compiling for a static binary(only depend on glibc2.x.x) for Linux Arm 64bit

thanks for your great work!

**Comment by JJawesomeJJ** [comment]
Can you tell me how to build,I try to edit the amt.js but I don't know how to build a new meshAgent,best wish!!

**Comment by krayon007** [comment]
If you are only updating amt.js, you only need to update the copy on the server, and it will pass it to the agent when it connects.

If you are wanting to build for aarch64 with glibc2.24, you can build it like this:
`make linux ARCHID=32`

**Comment by magicgis** [comment]
How to build in windows?

**Comment by krayon007** [comment]
> How to build in windows?

There is a Visual Studio solution and project file. You can build from within Visual Studio.
