### ISSUE TITLE
how is meshagent start?

### ISSUE THREAD

**Issue by gouchaoer** [Ylianst/MeshAgent#97]
how is the js files compiles into static meshagent?

**Comment by krayon007** [comment]
Some of the JS files are embedded into ILibDuktape_Polyfills.c
A few of them are directly provided by the server, inline with the meshcore.js provided by the server.

If you are wanted to test/update a .js file, just include an updated .js file in the same path as the agent binary, and restart the agent.

**Comment by krayon007** [comment]
You can also reference [this post](https://github.com/Ylianst/MeshAgent/issues/72) , where I described how to modify the JS files and re-link them back into the agent.
